### PR TITLE
Update for the most important part for auth

### PR DESCRIPTION
**Pull request by Ima8**
Add Env KONG_CASSANDRA_USERNAME and KONG_CASSANDRA_PASSWORD in Content.md for auth

### CODE REVIEW

**Comment by tianon** [comment]
cc @thibaultcha @gszr @p0pr0ck5 @thefosk

**Comment by tianon** [comment]
Waiting for a Kong maintainer to weigh in.

**Comment by thibaultcha** [comment]
I wonder why this change is necessary. Cassandra does not require authentication by default, or does it in an image you've used?

Additionally, I wouldn't consider using the `cassandra` superuser (with a default password) good practice, and thus likely something we would rather not advertise, especially in public facing documentation such as this.

**Comment by Ima8** [comment]
I spend more than 1 hour to find a way how auth via this Docker file. In the end, I try and try random the name of env. Y_Y.

**Comment by thibaultcha** [comment]
@Ima8 I had no issues running the example commands from this manual:

```
$ docker run -d --name kong-database \
                -p 9042:9042 \
                cassandra:3
Unable to find image 'cassandra:3' locally
3: Pulling from library/cassandra
be8881be8156: Pull complete 
fb2c677ef354: Pull complete 
bba7d7818fb8: Pull complete 
233a12098077: Pull complete 
3446f702d0d1: Pull complete 
2e3b739ed5d5: Pull complete 
6d104fb5620d: Pull complete 
458446f55982: Pull complete 
9d44379168d2: Pull complete 
e191856325d3: Pull complete 
Digest: sha256:17205a96d799a09d91a47b49b4bf98f3f28992f44077d5e6edab829e4655ef02
Status: Downloaded newer image for cassandra:3
e29359dc2d840196d327ba3be659ebd45ba0d42602cc2229e2eacfd8975470b9
```

```
$ docker run --rm \
    --link kong-database:kong-database \
    -e "KONG_DATABASE=cassandra" \
    -e "KONG_PG_HOST=kong-database" \
    -e "KONG_CASSANDRA_CONTACT_POINTS=kong-database" \
    kong:latest kong migrations up
Unable to find image 'kong:latest' locally
latest: Pulling from library/kong
a073c86ecf9e: Pull complete 
fe9db5a53243: Pull complete 
0cdea2e53386: Pull complete 
Digest: sha256:e5b1cfb2107d2a4018b1364536fdd4af7d2755962a2c53ddd966b27c7680b962
Status: Downloaded newer image for kong:latest
2018/08/22 00:30:23 [warn] You are using Cassandra but your 'db_update_propagation' setting is set to '0' (default). Due to the distributed nature of Cassandra, you should increase this value.
migrating core for keyspace kong
could not switch to kong keyspace ([Invalid] Keyspace 'kong' does not exist), attempting to create it
successfully created kong keyspace
core migrated up to: 2015-01-12-175310_skeleton
core migrated up to: 2015-01-12-175310_init_schema
core migrated up to: 2015-11-23-817313_nodes
core migrated up to: 2016-02-25-160900_remove_null_consumer_id
core migrated up to: 2016-02-29-121813_remove_ttls
core migrated up to: 2016-09-05-212515_retries_step_1
core migrated up to: 2016-09-05-212515_retries_step_2
core migrated up to: 2016-09-16-141423_upstreams
core migrated up to: 2016-12-14-172100_move_ssl_certs_to_core
core migrated up to: 2016-11-11-151900_new_apis_router_1
core migrated up to: 2016-11-11-151900_new_apis_router_2
core migrated up to: 2016-11-11-151900_new_apis_router_3
core migrated up to: 2017-01-24-132600_upstream_timeouts
core migrated up to: 2017-01-24-132600_upstream_timeouts_2
core migrated up to: 2017-03-27-132300_anonymous
core migrated up to: 2017-04-04-145100_cluster_events
core migrated up to: 2017-05-19-173100_remove_nodes_table
core migrated up to: 2017-07-28-225000_balancer_orderlist_remove
core migrated up to: 2017-11-07-192000_upstream_healthchecks
core migrated up to: 2017-10-27-134100_consistent_hashing_1
core migrated up to: 2017-11-07-192100_upstream_healthchecks_2
core migrated up to: 2017-10-27-134100_consistent_hashing_2
core migrated up to: 2017-09-14-140200_routes_and_services
core migrated up to: 2017-10-25-180700_plugins_routes_and_services
core migrated up to: 2018-02-23-142400_targets_add_index
core migrated up to: 2018-03-22-141700_create_new_ssl_tables
core migrated up to: 2018-03-26-234600_copy_records_to_new_ssl_tables
core migrated up to: 2018-03-27-002500_drop_old_ssl_tables
core migrated up to: 2018-03-16-160000_index_consumers
core migrated up to: 2018-05-17-173100_hash_on_cookie
migrating response-transformer for keyspace kong
response-transformer migrated up to: 2016-03-10-160000_resp_trans_schema_changes
migrating ip-restriction for keyspace kong
ip-restriction migrated up to: 2016-05-24-remove-cache
migrating statsd for keyspace kong
statsd migrated up to: 2017-06-09-160000_statsd_schema_changes
migrating jwt for keyspace kong
jwt migrated up to: 2015-06-09-jwt-auth
jwt migrated up to: 2016-03-07-jwt-alg
jwt migrated up to: 2017-07-31-120200_jwt-auth_preflight_default
jwt migrated up to: 2017-10-25-211200_jwt_cookie_names_default
jwt migrated up to: 2018-03-15-150000_jwt_maximum_expiration
migrating cors for keyspace kong
cors migrated up to: 2017-03-14_multiple_orgins
migrating basic-auth for keyspace kong
basic-auth migrated up to: 2015-08-03-132400_init_basicauth
migrating key-auth for keyspace kong
key-auth migrated up to: 2015-07-31-172400_init_keyauth
key-auth migrated up to: 2017-07-31-120200_key-auth_preflight_default
migrating ldap-auth for keyspace kong
ldap-auth migrated up to: 2017-10-23-150900_header_type_default
migrating hmac-auth for keyspace kong
hmac-auth migrated up to: 2015-09-16-132400_init_hmacauth
hmac-auth migrated up to: 2017-06-21-132400_init_hmacauth
migrating datadog for keyspace kong
datadog migrated up to: 2017-06-09-160000_datadog_schema_changes
migrating tcp-log for keyspace kong
tcp-log migrated up to: 2017-12-13-120000_tcp-log_tls
migrating acl for keyspace kong
acl migrated up to: 2015-08-25-841841_init_acl
migrating response-ratelimiting for keyspace kong
response-ratelimiting migrated up to: 2015-08-21_init_response-rate-limiting
response-ratelimiting migrated up to: 2016-08-04-321512_response-rate-limiting_policies
response-ratelimiting migrated up to: 2017-12-19-120000_add_route_and_service_id_to_response_ratelimiting
migrating request-transformer for keyspace kong
request-transformer migrated up to: 2016-03-10-160000_req_trans_schema_changes
migrating rate-limiting for keyspace kong
rate-limiting migrated up to: 2015-08-03-132400_init_ratelimiting
rate-limiting migrated up to: 2016-07-25-471385_ratelimiting_policies
rate-limiting migrated up to: 2017-11-30-120000_add_route_and_service_id
migrating oauth2 for keyspace kong
oauth2 migrated up to: 2015-08-03-132400_init_oauth2
oauth2 migrated up to: 2015-08-24-215800_cascade_delete_index
oauth2 migrated up to: 2016-02-29-435612_remove_ttl
oauth2 migrated up to: 2016-04-14-283949_serialize_redirect_uri
oauth2 migrated up to: 2016-07-15-oauth2_code_credential_id
oauth2 migrated up to: 2016-09-19-oauth2_code_index
oauth2 migrated up to: 2016-09-19-oauth2_api_id
oauth2 migrated up to: 2016-12-15-set_global_credentials
oauth2 migrated up to: 2017-10-19-set_auth_header_name_default
oauth2 migrated up to: 2017-10-11-oauth2_new_refresh_token_ttl_config_value
oauth2 migrated up to: 2018-01-09-oauth2_c_add_service_id
66 migrations ran
waiting for Cassandra schema consensus (10000ms timeout)...
Cassandra schema consensus: reached
```

```
$ docker run -d --name kong \
    --link kong-database:kong-database \
    -e "KONG_DATABASE=cassandra" \
    -e "KONG_CASSANDRA_CONTACT_POINTS=kong-database" \
    -e "KONG_CASSANDRA_USERNAME=cassandra" \
    -e "KONG_CASSANDRA_PASSWORD=cassandra" \
    -e "KONG_PROXY_ACCESS_LOG=/dev/stdout" \
    -e "KONG_ADMIN_ACCESS_LOG=/dev/stdout" \
    -e "KONG_PROXY_ERROR_LOG=/dev/stderr" \
    -e "KONG_ADMIN_ERROR_LOG=/dev/stderr" \
    -e "KONG_ADMIN_LISTEN=0.0.0.0:8001" \
    -e "KONG_ADMIN_LISTEN_SSL=0.0.0.0:8444" \
    -p 8000:8000 \
    -p 8443:8443 \
    -p 8001:8001 \
    -p 8444:8444 \
>   kong:latest
ae15112ebbf59d6e9c3d8ab9fc41756007c31d3b658dce4302a5ea028aa92552
chasum@x1c ~ $ docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED              STATUS              PORTS                                                                NAMES
ae15112ebbf5        kong:latest         "/docker-entrypoint.…"   3 seconds ago        Up 2 seconds        0.0.0.0:8000-8001->8000-8001/tcp, 0.0.0.0:8443-8444->8443-8444/tcp   kong
e29359dc2d84        cassandra:3         "docker-entrypoint.s…"   About a minute ago   Up About a minute   7000-7001/tcp, 7199/tcp, 9160/tcp, 0.0.0.0:9042->9042/tcp            kong-database
```

If your Cassandra image requires authentication, that is another issue. The goal of this document is to provide a 2 minutes quickstart for new users to run the Kong image. Cassandra authn/authz isn't an appropriate topic (especially when not required by default as demonstrated above).

The `cassandra_username` and `cassandra_password` configuration values are properly documented on our website for more advanced users: https://docs.konghq.com/0.14.x/configuration/#cassandra-settings

**Comment by Ima8** [comment]
> The cassandra_username and cassandra_password configuration values are properly documented on our website for more advanced users: https://docs.konghq.com/0.14.x/configuration/#cassandra-settings

We can't use 'cassandra_username' as a environment values right? It need to use KONG_CASSANDRA_USERNAME

My problem is i can't find the place that say what i should fill.

**Pull request closed without merging**
