### PR TITLE
Update sentry docs

### PR DESCRIPTION
**Pull request by mattrobenolt**
Fixes getsentry/docker-sentry#42

### CODE REVIEW

**Comment by yosifkit** [comment]
Can you move it to `content.md`? Readme is generated from there.

**Comment by mattrobenolt** [comment]
Oh, derp. Yeah, one minute. :)

**Comment by mattrobenolt** [comment]
@yosifkit Should be good now.

**Comment by yosifkit** [comment]
Thanks!  LGTM

**Pull request merged**
