### PR TITLE
Update the Fedora docs

### PR DESCRIPTION
**Pull request by maxamillion**
Signed-off-by: Adam Miller maxamillion@fedoraproject.org

### CODE REVIEW

**Comment by maxamillion** [comment]
I'm not sure I understand the Travis failure message. It says that a README.md changed and that's apparently a failure?

**Comment by yosifkit** [comment]
It's just to help users realize that they need to edit `content.md` since the readme is periodically regenerated by a bot.  I assume you just ran the update script after changing the content?  That will be fine.  Any other changes to readme will get lost.

**Comment by yosifkit** [comment]
LGTM

**Comment by maxamillion** [comment]
Why wasn't this merged before the merge conflict happened?

**Comment by tianon** [comment]
Merged by hand in c1d839e489a1bfbd5d39b30d50214a528eb51419 (just removed the `README.md` changes -- the bot will update that file for us shortly before it pushes the changes to the Hub).

**Pull request closed without merging**
