### PR TITLE
Update a few minor Alpine bits to reflect the new reality

### PR DESCRIPTION
**Pull request by tianon**
cc @ncopa

These docs could really use a lot more care and attention, but this at least brings them in line with the move to https://github.com/alpinelinux/docker-alpine and your official maintenance.  Does this look OK?  Anything you'd like me to change while I'm in here?  (I don't mind making more changes if you want, or if you'd rather take over and make these changes yourself -- happy to help!)

### CODE REVIEW

**Comment by tianon** [comment]
Friendly ping @ncopa :heart:

**Comment by ncopa** [comment]
Sorry. Almost completely forgot this.

@dunielpls did you have something on updating documentation for official alpine docker images?

**Comment by dunielpls** [comment]
Yeah, I have a few commits sitting around, but I'm okay with this being merged until I've managed to work out some of the nooks and crannies.

The build script has been renamed, and I suspect there are other changes to the build process that makes some of the documentation from gliderlabs/docker-alpine obsolete.

**Comment by ncopa** [comment]
Ok. lets merge this as is.

**Comment by tianon** [comment]
Awesome, thanks folks! ♥️

(Will look forward to future PRs improving this more 👍)

**Pull request merged**
