### PR TITLE
Updates to websphere-liberty docs

### PR DESCRIPTION
**Pull request by davidcurrie**
Add details of shared class cache usage and note on use of boot2docker ip (as per comment submitted on Docker Hub).

### CODE REVIEW

**Comment by yosifkit** [comment]
LGTM

**Comment by davidcurrie** [comment]
Document move from IBM JRE to OpenJRE as per https://github.com/docker-library/official-images/pull/939 (at which point the previous update on shared class usage is no longer applicable).

**Comment by yosifkit** [comment]
New parts LGTM too :smile:

**Comment by tianon** [comment]
:+1:

**Pull request merged**
