### PR TITLE
Expand our "repo-info" blurb to link to both the "local" and "remote" directories (and explain a little bit about what each is)

### PR DESCRIPTION
**Pull request by tianon**

### CODE REVIEW

**Comment by tianon** [comment]
Example blurb:

For detailed information about each of the above supported tags, please see [the `repos/alpine/remote` directory (gathered from the Docker Hub API; transfer sizes, layer details, etc)](https://github.com/docker-library/repo-info/tree/master/repos/alpine/remote) and [the `repos/alpine/local` directory (gathered from the image after it is pulled; installed packages, etc)](https://github.com/docker-library/repo-info/tree/master/repos/alpine/local) in [the `docker-library/repo-info` GitHub repo](https://github.com/docker-library/repo-info).

**Comment by yosifkit** [comment]
Those are some really long links. So my initial thought for improving clarity was something like this:

For detailed information about each of the above supported tags, please see the following from the [`docker-library/repo-info` GitHub repo](https://github.com/docker-library/repo-info):

 - [`repos/%%REPO%%/remote` directory](https://github.com/docker-library/repo-info/tree/master/repos/%%REPO%%/remote)
  - gathered from the Docker Hub API
  - transfer sizes, layer details, etc
 - [`repos/%%REPO%%/local` directory](https://github.com/docker-library/repo-info/tree/master/repos/%%REPO%%/local)
  - gathered from the image after it is pulled
  - installed packages, creation date, architecture, environment variables, etc


But then we discussed where it goes on the hub page and it makes more sense to minimize this part to just a sentence and then link to `repo-info/%%REPO%%/` and have a Readme file there that describes what is in each folder.  This other readme can then grow and improve as the data in repo-info changes and improves.

**Comment by tianon** [comment]
A bit long in the works, but here's my proposal for the structure of that `repos/%%REPO%%/README.md` file:

# `alpine`

This directory contains additional information about the published artifacts of the `alpine` official image.

- [the `remote` directory](remote/):
  - gathered from the Docker Hub/Registry API
  - image digests/blobs, transfer sizes, image metadata, etc.

- [the `local` directory](local/):
  - inspected from the image on-disk after it is pulled
  - installed packages, creation date, architecture, environment variables, detected licenses, etc.

**Comment by tianon** [comment]
Alright, this is updated to account for https://github.com/docker-library/repo-info/issues/12 now. :+1:

**Comment by tianon** [comment]
(probably easiest to review commit-by-commit, since the second commit reorders these two paragraphs)

**Pull request merged**
