### PR TITLE
[nats] Release v1.4.1

### PR DESCRIPTION
**Pull request by kozlovic**
Details can be found [here](https://github.com/nats-io/gnatsd/releases/tag/v1.4.1)

Signed-off-by: Ivan Kozlovic <ivan@synadia.com>

### CODE REVIEW

**Comment by kozlovic** [comment]
@yosifkit @tianon Hey guys, sorry to bother you, would you know how we can change the logos that appear at top of the page [here](https://hub.docker.com/_/nats) and [here](https://hub.docker.com/_/nats-streaming).

As you can see in each of those repos, we have provided our `logo.png` and it is correctly displayed when one scrolls down past the supported tags and quick reference sections, but not at top of the page or as the result of a search for `nats` like this: `https://hub.docker.com/search?q=nats&type=image`.

Thanks!

**Comment by yosifkit** [comment]
Not a problem! We have been working with the folks on Docker Hub to better use the logo files from docs, but it hasn't happened yet. For now the best way is to go through support@docker.com.

**Comment by kozlovic** [comment]
Thanks!

**Comment by derekcollison** [comment]
I just submitted a support ticket as well. This is still not done. Let us know what we need to do different to get this done. Thanks.

**Comment by tianon** [comment]
It's unfortunately completely outside our control; as far as we know, this is still something that has to change in the Hub directly (and there's no API for us to hit), so Docker's support channels are all we've got.

**Comment by derekcollison** [comment]
We did support email as you suggested, got nothing back. Was hoping you all would have more pull maybe. Been multiple months outstanding.

**Comment by derekcollison** [comment]
ok sent a new support email.. This is kinda silly IMO.

**Comment by tianon** [comment]
I'm definitely sorry about it, and wish there was more we could do, but it's fully outside our control. :disappointed:

**Pull request merged**
