### PR TITLE
Add in docs for NATS

### PR DESCRIPTION
**Pull request by derekcollison**
Docs for NATS, referencing https://github.com/docker-library/official-images/pull/961

### CODE REVIEW

**Comment by tianon** [comment]
Mind applying the patch in the Travis output? (or using `./markdownfmt.sh -w nats/content.md` to apply it more directly via the tool itself)

Otherwise, LGTM.

**Comment by derekcollison** [comment]
done. I used the tool directly and it made the change, but someone here ran
the script which put it back.. ;)

**Comment by yosifkit** [comment]
LGTM

**Comment by tianon** [comment]
:+1:

**Pull request merged**
