### PR TITLE
RabbitMQ: Add instructions on how to set default user and password 

### PR DESCRIPTION
**Pull request by workmaster2n**
Include instructions on README showing how to use RABBITMQ_DEFAULT_USER and RABBITMQ_DEFAULT_PASS environmental variables

fixes: https://github.com/docker-library/rabbitmq/issues/34

### CODE REVIEW

**Comment by yosifkit** [comment]
Can you put that in content.md? README.md is generated and is handled by the docker-library-bot.

**Comment by workmaster2n** [comment]
Done. Also added section on vhost configuration.

My git knowledge isn't that great, so let me know if I messed up a commit or something. I couldn't think how to reset `README.md`, so I just deleted the lines I added and moved them to `content.md`

**Comment by yosifkit** [comment]
Great! Thanks! Just one more thing is the failing travis test. Looks like you just need to swap to a tab for the code blocks rather than spaces.  And delete the spaces from the empty line.

**Comment by workmaster2n** [comment]
Done. Thanks for the heads up!

**Comment by yosifkit** [comment]
LGTM

**Comment by tianon** [comment]
LGTM

**Pull request merged**
