### PR TITLE
Update README description for Apache Solr

### PR DESCRIPTION
**Pull request by gerlowskija**
Keeps these descriptions up to date with changes the Apache Solr project made recently in their README, documentation, website, etc.

Additional context at:
  - https://solr.apache.org/
  - https://issues.apache.org/jira/browse/SOLR-16295
  - https://github.com/apache/solr/pull/2692

### CODE REVIEW

**Comment by whalelines** [comment]
@gerlowskija, the checks seem to be failing, can you address?

Thoughts @shalinmangar @dsmiley @janhoy @houstonputman?

**Comment by gerlowskija** [comment]
Yep, should be fixed - looks like the GH Action needs approval to re-run, but `./.ci/check-short.sh` now passes locally on my branch at least.

Thanks for giving it a look @whalelines !

**Review by tianon — APPROVED** [review]

**Comment by tianon** [comment]
Merging based on the wording matching the upstream references -- if one of the `solr` image maintainers disagree, we're happy to revert/update (a new PR would be appreciated). :+1:

**Comment by HoustonPutman** [comment]
This is approved, sorry for missing it earlier

**Pull request merged**
