### PR TITLE
Add OrientDB to official images - docs

### PR DESCRIPTION
**Pull request by robfrank**
Add docs for OrientDB docker image usage.

### CODE REVIEW

**Comment by robfrank** [comment]
I'm sorry, but I can't uderstand what's wrong with this PR.

**Comment by tianon** [comment]
No worries!  It looks like `markdownfmt` (https://github.com/docker-library/docs/blob/master/markdownfmt.sh) is just a little unhappy about the exact whitespace in use -- once we're happy with https://github.com/docker-library/official-images/pull/1432, I can take over on formatting here if you'd rather.

(If you want to mess with it yourself some more, the `markdownfmt.sh` script at the top-level of this repo _should_ be able to help; something like `./markdownfmt.sh -d orientdb/content.md` should give you a pretty good idea of the things it's unhappy about so you can cycle locally without waiting for Travis.)

**Comment by robfrank** [comment]
thank, I'll try to fix formatting!

**Comment by robfrank** [comment]
reformatted!

**Comment by tianon** [comment]
LGTM :+1:

**Comment by yosifkit** [comment]
LGTM

**Pull request merged**
