### PR TITLE
Adds example on setting a docroot with Apache

### PR DESCRIPTION
**Pull request by themccallister**
Addresses comments made here: https://github.com/docker-library/php/issues/246

### CODE REVIEW

**Comment by tianon** [comment]
Rebased and applied some minor tweaks; thanks! :+1:

**Comment by mortenson** [comment]
Have you tried this out yet? I get this error every time:
```
ERROR: for ame_php_1  Cannot start service php: oci runtime error: container_linux.go:262: starting container process caused "chdir to cwd (\"/var/www/html\") set in config.json failed: no such file or directory"


ERROR: for php  Cannot start service php: oci runtime error: container_linux.go:262: starting container process caused "chdir to cwd (\"/var/www/html\") set in config.json failed: no such file or directory"

ERROR: Encountered errors while bringing up the project.
```

**Comment by themccallister** [comment]
@mortenson can you provide an example Dockerfile?

**Comment by mortenson** [comment]
@themccallister Yes, my Dockerfile (in ./php) looks like this:
```
FROM php:7.1-apache
ENV APACHE_DOCUMENT_ROOT /var/www/web
RUN sed -ri -e 's!/var/www/html!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/sites-available/*.conf
RUN sed -ri -e 's!/var/www/!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/apache2.conf /etc/apache2/conf-available/*.conf
```
then in docker-compose.yml I mount the `/var/www/web` volume like this:
```
version: '3'
services:
  php:
    build: ./php
    ports:
      - '8080:80'
    volumes:
      - ./code:/var/www/web
```

**Pull request merged**
