### PR TITLE
correct formatting errors in php-zendserver README.md (content.md)

### PR DESCRIPTION
**Pull request by devvyn**
Missing line breaks caused heading and paragraphs to bleed together.
Missing line breaks caused lists to become run-on paragraphs.
Space-hyphen-space replaced with unicode dash in cases when a dash would normally be used in English

Signed off by Devvyn Murphy

### CODE REVIEW

**Comment by yosifkit** [comment]
Can you move this to `content.md`?  Readme is generated periodically by a jenkins task.

**Comment by devvyn** [comment]
That makes sense. I'm not sure if pushing a squashed version of the changes complicated anything. I can submit a new pull request if needed. I hope this helps.

**Comment by yosifkit** [comment]
Looks like the build is failing on some formatting.  We use tianon's fork of markdownfmt to standardize the formatting.  The diff is in the build details or can be seen locally by running `./markdownfmt.sh -d` which will run a docker container with a bind mount.

**Comment by devvyn** [comment]
I ran `content.md` through `tianon/markdownfmt` Docker container and got the diff down to zero lines, but I don't understand the new final error in the CI build details. I'm hoping that's an expected condition, but let me know if I can help some more with this.

**Comment by yosifkit** [comment]
Yeah, that looks like you are just based of an older part of the master branch so it gets hung up on `readme.md` changes.

LGTM

**Pull request merged**
