### PR TITLE
Add LogicalDOC

### PR DESCRIPTION
**Pull request by car031**

### CODE REVIEW

**Comment by car031** [comment]
it says check-markdownfmt.sh exited with 1. But no hints are shown. Can osmeone tell me what is wring in our content.md ?

**Comment by car031** [comment]
Please, can someone help me in understanding why my content.md does not pass the check-markdownfmt.sh ?

**Comment by Moghedrin** [comment]
Next time, you should probably download [markdownfmt.sh](https://github.com/docker-library/docs/blob/master/markdownfmt.sh) and test locally, rather than spamming commits. XD That being said, glad you got it figured out!

LGTM, pending acceptance of docker-library/official-images#2897!

**Comment by yosifkit** [comment]
Closing since image PR is closed: https://github.com/docker-library/official-images/pull/2897

**Pull request closed without merging**
