### PR TITLE
cache dependencies to optimize workflow

### PR DESCRIPTION
**Pull request by jdrouet**
Use `cargo fetch` to download the dependencies and keep them in a layer to improve the development process.

### CODE REVIEW

**Comment by tianon** [comment]
cc `rust` image maintainer @sfackler

(also, for this to be in a format we can accept, assuming @sfackler is :+1: on the change, you'll need to move the edit from `README.md` over to `content.md` since the former is a generated artifact)

**Comment by tianon** [comment]
IMO this is a pretty decent case of a good "exercise for the reader" but it's really your call, @sfackler :+1:

**Comment by sfackler** [comment]
I agree that this is more complexity than is necessary for a hello world example.

**Comment by tianon** [comment]
Ok, makes sense. :+1:

Thank you for the contribution! :heart:

**Pull request closed without merging**
