### PR TITLE
Update forwarded ports in example docker run commands

### PR DESCRIPTION
**Pull request by udkyo**

### CODE REVIEW

**Comment by tianon** [comment]
There's a lot of unrelated whitespace and formatting changes in here -- was that intentional? :grimacing:

**Comment by udkyo** [comment]
Interesting, let's go with 'no' - I've pushed a new commit with only the `docker run` lines changed!

**Comment by tianon** [comment]
Nice, looks fine to me -- should this wait for https://github.com/couchbase/docker/pull/193, or is it fine to go first?

**Comment by udkyo** [comment]
Thanks tianon, this is fine to merge, please feel free to do so.

**Pull request merged**
