### PR TITLE
[Nextcloud] Add Play with Docker button

### PR DESCRIPTION
**Pull request by tilosp**
nextcloud/docker#166

### CODE REVIEW

**Comment by tilosp** [comment]
@tianon please review

**Comment by tianon** [comment]
That `cron` service is really hacky -- how are users normally expected to implement `cron` for Nextcloud, especially in a Docker context?

**Comment by tilosp** [comment]
@tianon At the moment there are two ways. One is the hacky docker-compose one and the other one is this [Dockerfile](https://github.com/nextcloud/docker/blob/master/.examples/dockerfiles/cron/apache/Dockerfile).
We could make the docker-compose way less hacky by adding the script to the container. And then just change the entrypoint in the `docker-compose.yml` for the cron container.

**Comment by tianon** [comment]
How about this?
```dockerfile
FROM nextcloud:apache

# busybox's crond is more flexible than what's provided by the "cron" package
# (especially around logging)
RUN apt-get update && apt-get install -y busybox-static && rm -rf /var/lib/apt/lists/*

RUN echo '*/15 * * * * www-data php -f /var/www/html/cron.php' > /etc/crontab

WORKDIR /var/spool/cron/crontabs
CMD ["busybox", "crond", "-f", "-l", "0", "-L", "/dev/stdout"]
```

Combined with:
```yaml
version: '3.2'

services:
  db:
    image: postgres
    restart: always
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud
      - POSTGRES_PASSWORD=nextcloud

  app:
    image: nextcloud
    restart: always
    ports:
      - 8080:80
    volumes:
      - nextcloud:/var/www/html
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud
      - POSTGRES_PASSWORD=nextcloud
    depends_on:
      - db

  cron:
    image: nextcloud:cron
    restart: always
    init: true
    volumes:
      - nextcloud:/var/www/html
    depends_on:
      - db

volumes:
  db:
  nextcloud:
```

You could even simply include `busybox-static` with the pre-configured `crontab` in the base `nextcloud` image, and add a `nextcloud-crond` script which is basically just:

```bash
#!/usr/bin/env bash
set -Eeuo pipefail
mkdir -p /var/spool/cron/crontabs
exec busybox crond -f -l 0 -L /dev/stdout "$@"
```

So you'd just use:
```yaml
    image: nextcloud
    command: nextcloud-crond
    init: true
```
(and `init: true` is only necessary if you want to be able to Ctrl+C to kill it interactively -- it seems to respond fine to the SIGTERM that `docker stop` sends without `--init`)

**Comment by tilosp** [comment]
@pierreozoux What do you think?

**Comment by pierreozoux** [comment]
I like the second option with the `nextcloud-crond` script and the different command in the compose, I find it nicer.
(yes, it was hacky, but still works :) also had a lot of trouble to find a nice crond script that was minimal for docker, but now I'll know! Thanks!)

**Comment by tilosp** [comment]
Started to implement the second option in https://github.com/nextcloud/docker/pull/220

**Pull request closed without merging**
