### PR TITLE
Deprecate "sourcemage" due to maintainer inactivity

### PR DESCRIPTION
**Pull request by tianon**
cc @vaygr -- if we don't hear from you shortly, we'll be merging this :pray:

### CODE REVIEW

**Comment by vaygr** [comment]
Hi @tianon, we're actually working on the new docker image which is based on the recent security update for the latest grimoire we got on [Oct 1](http://sourcemage.org/News/grimoire-0-62-6/).

2 weeks max :sweat_smile: 

p.s. thanks for your patience

**Comment by yosifkit** [comment]
We look forward to the updates!  (I'll close this PR since it is no longer needed)

**Comment by tianon** [comment]
Hey @vaygr -- we're at two weeks now :wink:

What's our update status? :pray:

**Comment by vaygr** [comment]
@tianon yeah, this has been postponed till at least the very beginning of November, due to recent security issues uncovered. We're waiting for [curl update](https://curl.haxx.se/mail/lib-2016-10/0076.html) right now, then we will come up with new chroot image, which will be used to build an updated docker image. Stay tuned!

**Comment by tianon** [comment]
ping @vaygr :wink:

**Comment by vaygr** [comment]
yep, we've just got a couple of [sequential](http://sourcemage.org/News/grimoire-0-62-8/) [releases](http://sourcemage.org/News/grimoire-0-62-9/), so the new image should be ready within a week.

**Comment by vaygr** [comment]
Slightly delayed, but the image is being prepared, should be ready by EOD.

**Comment by vaygr** [comment]
Raised the PR here: https://github.com/docker-library/official-images/pull/2403

**Comment by vaygr** [comment]
And for docs: https://github.com/docker-library/docs/pull/757

**Pull request closed without merging**
