### PR TITLE
Add HTTP/2 info to nginx

### PR DESCRIPTION
**Pull request by jareddlc**
add a section about HTTP/2 to nginx docs

### CODE REVIEW

**Comment by yosifkit** [comment]
Seem fine to me, but I'll leave it up to the maintainer, @thresheek.

**Comment by thresheek** [comment]
I am against that change, since current nginx:latest (since 1.13.0 and 1.12.0) ship with http2 enabled due to usage of debian stretch base image.  This makes this change incorrect.

**Comment by tianon** [comment]
Thanks for reviewing @thresheek :heart:

**Comment by jareddlc** [comment]
@thresheek here is what i've found:

```
$ docker run -it --rm --name some-nginx nginx:latest bash
root@9db74cfc1b6b:/# nginx -V
nginx version: nginx/1.13.7
built by gcc 6.3.0 20170516 (Debian 6.3.0-18)
built with OpenSSL 1.1.0f  25 May 2017
```

and per the nginx docs: (http://nginx.org/en/docs/http/ngx_http_v2_module.html)

```
Note that accepting HTTP/2 connections over TLS requires the “Application-Layer Protocol Negotiation” (ALPN) TLS extension support, which is available only since OpenSSL version 1.0.2. Using the “Next Protocol Negotiation” (NPN) TLS extension for this purpose (available since OpenSSL version 1.0.1) is not guaranteed to work.
```

**Comment by jareddlc** [comment]
@thresheek thanks for catching my mistake

**Pull request closed without merging**
