### PR TITLE
use google's dns as well

### PR DESCRIPTION
**Pull request by hutchic**
need a second dns specified otherwise we can't resolve the interenet

### CODE REVIEW

**Comment by tianon** [comment]
cc @slackpad

**Comment by slackpad** [comment]
Hi @hutchic this might be better done by adding a [`-recusor=8.8.8.8`](https://www.consul.io/docs/agent/options.html#_recursor) example. I think having multiple servers defined but not equivalent (one Internet and one .consul) would possibly result in multiple queries during normal operation, which isn't super ideal.

**Comment by hutchic** [comment]
@slackpad sure that would work I think that's what `progrium/consul` does. As currently coded / documented people aren't going to have a fun time following the docs verbatim

**Comment by tianon** [comment]
@hutchic did you want to update your PR with that change? :smile: :pray:

**Comment by hutchic** [comment]
I'm doubtful I will. I'm not actually using the container and if I was I'd just use the change from this PR over patching the actual image.

The way I see it this documentation change makes the docs correct / work now. I'd humbly suggest merge this change and make an issue on consul repository to add a `-recursor=8.8.8.8` at which time nuke this change from the docs

**Comment by slackpad** [comment]
I'll take a swing at adding a recursor config and testing it out.

**Comment by hutchic** [comment]
@slackpad just following up. If you added the recursor config we can probably close this PR

**Pull request closed without merging**
