### PR TITLE
Influxdb remove admin interface

### PR DESCRIPTION
**Pull request by rdxmb**
fixes https://github.com/docker-library/docs/issues/1136

### CODE REVIEW

**Comment by tianon** [comment]
cc @jsternberg :pray: (I guess this conflicts with / replaces #1141?  happy to help resolve these however you see fit)

**Comment by rdxmb** [comment]
@tianon why that?
https://github.com/docker-library/docs/pull/1141 -> telegraf image
this PR -> influxdb image

They do not conflict or replace, but complement each other.

**Comment by yosifkit** [comment]
Sorry, I think @tianon and I were both assuming without fully comprehending that they were for the same image, since it was the same port deprecation. :blush:

This PR has an extra, unrelated line at the end (it looks like text from a merge conflict line :wink:), and there is a useful blank line being removed at [132](https://github.com/docker-library/docs/pull/1390/files#diff-dbc83212c60edbaea4d9c39c6a0a8523L132).

**Comment by rdxmb** [comment]
> This PR has an extra, unrelated line at the end (it looks like text from a merge conflict line wink), and there is a useful blank line being removed at 132.

Oops. Fixed.

**Comment by rdxmb** [comment]
@Cultti fixed. Thanks!

**Pull request merged**
