### PR TITLE
Does some minor cleanups on the Consul docs.

### PR DESCRIPTION
**Pull request by slackpad**
Sorry I had a couple typos and cleanups to make once I saw merged docs on the hub. These are all minor edits.

### CODE REVIEW

**Comment by tianon** [comment]
LGTM

**Comment by slackpad** [comment]
Rolled a couple more tiny edits into this after hearing from a few folks :-)

**Comment by tianon** [comment]
:+1: still LGTM

cc @yosifkit

**Comment by slackpad** [comment]
Thanks!

**Comment by tianon** [comment]
:+1:

**Pull request merged**
