### PR TITLE
adoptopenjdk: add logo + formatting

### PR DESCRIPTION
**Pull request by gdams**

### CODE REVIEW

**Comment by gdams** [comment]
thanks for landing this, I've seen that the doc is now updated at https://hub.docker.com/_/adoptopenjdk but the main logo at the top is still the default one. Do I need to change something else?

**Comment by gdams** [comment]
If we have a choice it would be good to add https://adoptopenjdk.net/dist/assets/social-logo.png

**Comment by yosifkit** [comment]
Unfortunately the logo at the top is not controlled by us. I'll try poking someone at Docker Inc to see if they can tell the right people.

**Comment by gdams** [comment]
Thanks @yosifkit! It would be great to get the logo added! :)

**Pull request merged**
