### PR TITLE
Delete --link flag in the mysql doc.

### PR DESCRIPTION
**Pull request by seiyab**
Document of mysql image uses deprecated --link flag.
https://docs.docker.com/engine/userguide/networking/default_network/dockerlinks/

Avoided --link flag using docker network.

I worry about my English because I'm not an English speaker.

### CODE REVIEW

**Comment by yosifkit** [comment]
As much as I'd like to switch away from the _"may eventually be removed"_ `link` flag, it makes one time samples effortless to read and run. It also doesn't pollute the user's machine with random unused networks after they try out a demo. :disappointed:

**Comment by seiyab** [comment]
I see. I agree with you. 😞 

Now, I omitted docker network. How about this one ?
It doesn't create new network. However, the command may be complex.

**Comment by tianon** [comment]
See https://github.com/docker-library/docs/issues/786 for another discussion of this same topic.

I'm still a fan of `--link`, and my rationale for being so is in https://github.com/docker-library/docs/issues/786#issuecomment-350491848.

**Comment by ivor52** [comment]
from what i understand, then, there will be no update of the documentation?  i think the overall point is being missed.  as long as --link is supported, there is nothing wrong with using it since it is simpler to make examples.
however, this does not address the issue: once the --link option is removed (since it will be be if it's been deprecated), the documentation will be wrong and won't even work anymore.
i'm not sure i understand why a single example of using the new docker convention (specifying a network) cannot be included for completeness, not to mention that once --link does go away, the documentation will be already updated for the new scenario.

**Comment by tianon** [comment]
@ivor52 `--link` is deprecated, yes, but in documentation only (I'd call it a "soft deprecation")

For Docker's normal deprecation policy, the deprecated functionality needs to throw a warning for some number of releases before it's removed.  With `--link`, its usage is essentially only discouraged, not actually deprecated, and there's no current plan to remove that functionality which I'm aware of.

Currently, the full docs for all official images have no less than 104(!) usages of `--link`.  To suggest that _every_ one of those be updated to a long-form example that includes a full `docker network create ...` etc is pretty aggressive.  If/when `--link` is _actually_ deprecated, I'd likely be more in favor of adjusting the documentation to be more vague in those 104 places and to instead punt to some of Docker's upstream documentation for "how to configure containers to communicate with one another" (and instead simply describe what the built-in expectations or control knobs of the image are for using those Docker upstream features).

**Pull request closed without merging**
