### PR TITLE
Fix typos/spelling and uses of 'ROS 1' & 'ROS 2'

### PR DESCRIPTION
**Pull request by christophebedard**
There should be a space between "ROS" and "1" or "2".

### CODE REVIEW

**Comment by tianon** [comment]
cc @tfoote (`ros` image maintainer)

**Comment by tianon** [comment]
ping @tfoote

**Comment by christophebedard** [comment]
I can provide "proof" (& other previous PRs) that this PR enforces the correct use of "ROS 1"/"ROS 2" if that can make the process of modifying 13 lines simpler:

* https://www.ros.org/press-kit/
  > Specific versions of ROS should be specified by placing the release name or version number after the ROS name, separated by a space. For example, ROS Melodic, ROS Dashing, ROS 1, ROS 2.
* https://github.com/ros2/ros2_documentation/pull/543
* https://github.com/ros2/ros2_documentation/issues/753
* https://github.com/ros2/ros2_documentation/issues/781
* https://github.com/ros-planning/navigation.ros.org/pull/41
* https://github.com/ros2/rmw_cyclonedds/pull/195

**Review by tfoote — APPROVED** [review]
Thanks for the attention to detail.

**Pull request merged**
