### PR TITLE
Add link to latest node documentation

### PR DESCRIPTION
**Pull request by styfle**
This replaces most of the node contents with a link to the official docker-node repo README.

/cc @chorrell @SimenB 

This came up in discussion in https://github.com/nodejs/docker-node/pull/319 since that modifies the text of one of the variants.

### CODE REVIEW

**Comment by yosifkit** [comment]
If the nodejs docker working group agrees, it seems reasonable to me.

**Comment by SimenB** [comment]
I have nothing in particular against this.

/cc @Starefossen @pesho  @peterdavehello @LaurentGoderre @retrohacker

**Comment by pesho** [comment]
LGTM :+1: I also think this is the most sensible approach.

**Comment by chorrell** [comment]
LGTM 👍

**Comment by tianon** [comment]
Since we've got three official :+1:, I'm going to merge -- feel free to holler if I did a bad thing. :wink: :heart:

**Pull request merged**
