### PR TITLE
Fix typo in Nextcloud Apache reverse-proxy docs

### PR DESCRIPTION
**Pull request by jaylinski**
I hope this makes sense. The current description sounds a bit confusing to me.

### CODE REVIEW

**Comment by JBScoutBerlin** [comment]
I think you have send this PR to the wrong repo ;-)

**Comment by tianon** [comment]
cc @tilosp

**Comment by jaylinski** [comment]
@tilosp I have the following config running in production, so I can confirm that the doc-changes make sense.

```yaml
  nextcloud:
    image: nextcloud:20-apache
    volumes:
      - /srv/docker/volumes/nextcloud:/var/www/html
    networks:
      - home
    environment:
      NEXTCLOUD_ADMIN_USER: "admin"
      NEXTCLOUD_ADMIN_PASSWORD_FILE: /run/secrets/nextcloud_admin_password
      NEXTCLOUD_TRUSTED_DOMAINS: "nextcloud.xxx.com"
      TRUSTED_PROXIES: "10.0.0.0/8"
      APACHE_DISABLE_REWRITE_IP: 1
```

**Comment by jaylinski** [comment]
Friendly bump @tilosp

**Review by tilosp — APPROVED** [review]

**Pull request merged**
