### PR TITLE
Fix typo in Swift doc and add issues link

### PR DESCRIPTION
**Pull request by shahmishal**

### CODE REVIEW

**Comment by shahmishal** [comment]
@yosifkit Sorry not sure what the process is after creating the PR. Is it ok to mention you in the PR for review?

**Comment by shahmishal** [comment]
@tianon / @yosifkit Can you please review this PR? We would like to update the typo and the issues information.

**Comment by shahmishal** [comment]
The icon used on https://hub.docker.com/_/swift/ is wrong, where should I create an issue? 

Current icon:
screen shot 2018-12-17 at 12 15 54 pm

It should be:
screen shot 2018-12-14 at 10 06 58 am

**Comment by yosifkit** [comment]
As for the logo on the Docker Hub: 
> [the logo.png] does not directly control the image at the top of the page (or on search results). I'll slack message some Docker folks to see if they can also update their copy.
>
> https://github.com/docker-library/docs/pull/1384#issuecomment-448819781

**Comment by shahmishal** [comment]
@yosifkit Thanks!

**Pull request merged**
