### PR TITLE
Move the theoretical best-effort support line from Docker 1.0 up to Docker 1.6

### PR DESCRIPTION
**Pull request by tianon**
Also, add a link to the Docker docs for installation.

### CODE REVIEW

**Comment by psftw** [comment]
sounds reasonable to me based on a quick look at the data.  Pre-1.5 is a blip, and even 1.5 clients are not hitting hub that much these days.

**Comment by tianon** [comment]
So maybe we could kick up to 1.6?

**Comment by psftw** [comment]
Sure.  Labels anyone?  *ducks and hides*

**Comment by tianon** [comment]
Done!

**Comment by yosifkit** [comment]
LGTM

**Pull request merged**
