### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by PavelVanecek**
typo

### CODE REVIEW

**Comment by yosifkit** [comment]
Thanks!  Though that is part of the generated section and needs to apply to every `README.md`.  Can you put the change just in [`/.template-helpers/user-feedback.md`](https://github.com/docker-library/docs/blob/0f644edd00fc28b49fea541e90585ad5e4d3ee24/.template-helpers/user-feedback.md)?  Then we can run update to regenerate the rest.

**Comment by tianon** [comment]
This has got to be one of my favorite typos ever since it's gone _so long_ unnoticed. :smile:

**Comment by PavelVanecek** [comment]
Thanks @yosifkit. Do I need to remove the first commit or the file will overwrite?

**Comment by yosifkit** [comment]
No, thats fine.  It'll still work. LGTM

**Comment by tianon** [comment]
LGTM

**Pull request merged**
