### PR TITLE
Rewrite "generate-tag-details.sh" in Perl for better correctness and cooler features

### PR DESCRIPTION
**Pull request by tianon**

### CODE REVIEW

**Comment by tianon** [comment]
(Thanks for the shove, @md5; :heart:)

**Comment by tianon** [comment]
https://github.com/infosiftr/docker-library-docs/blob/generate-tag-details.pl/hylang/tag-details.md :heart_eyes:

**Comment by md5** [comment]
Nice!

It might be nice to compress the whitespace in the `RUN` commands since the `\n` characters are being elided anyways. It would also be nice if the "bytes" output were comma-delimited, but it doesn't look like `printf` supports that and I don't think it's worth writing custom code for it.

Otherwise, this LGTM :+1:

**Comment by tianon** [comment]
Excellent idea on making `RUN` lines easier to read, @md5 :+1:

Compare: https://github.com/infosiftr/docker-library-docs/blob/d690a62d538b20f31ea3182117e9a579cf295b37/hylang/tag-details.md#57b905b0cff8c61e420002921bc22a8a2022b6d6fc70ad2a995e39859399d778

To: https://github.com/infosiftr/docker-library-docs/blob/7cd29c1f6a29b86fe75001d8fd40b48d060cb3bd/hylang/tag-details.md#57b905b0cff8c61e420002921bc22a8a2022b6d6fc70ad2a995e39859399d778

Better? :smile:

**Comment by yosifkit** [comment]
LGTM

**Comment by md5** [comment]
:metal:

**Pull request merged**
