### PR TITLE
Updated with more relevant quickstart information

### PR DESCRIPTION
**Pull request by ceejatec**
This change passes markdownfmt -d *except* for three `code` elements that contain nested backticks. I tried many variations and could not find one that markdownfmt liked. In at least one case, markdownfmt suggested a change, but when I made that change it rejected it in a different way. So I eventually gave up. The three blocks in question seem to render OK on GitHub at least. Hopefully this is either acceptable as-is or you can tell me what markdown incantation to use.

### CODE REVIEW

**Comment by tianon** [comment]
Arg, that's irritating; sorry for the trouble!  This diff seems to do the trick here locally: (tabs for indentation though, not spaces -- GitHub's comments don't preserve tabs :disappointed:)
```diff
diff --git a/couchbase/content.md b/couchbase/content.md
index ae43889..a9a538c 100644
--- a/couchbase/content.md
+++ b/couchbase/content.md
@@ -33,7 +33,7 @@ Walk through the Setup wizard and accept the default values.
 
 N1QL is the SQL based query language for Couchbase Server. Simply switch to the Query tab on the Web Console at `http://localhost:8091` and run the following N1QL Query in the query window:
 
-```SELECT name FROM `beer-sample` WHERE brewery_id ="mishawaka_brewing";```
+       SELECT name FROM `beer-sample` WHERE brewery_id ="mishawaka_brewing";
 
 You can also execute N1QL queries from the commandline. To run a query from command line query tool, run the interactive shell on the container:
 
@@ -43,7 +43,7 @@ Then, navigate to the `bin` directory under Couchbase Server installation and ru
 
 `/opt/couchbase/bin/cbq`
 
-```cbq> SELECT name FROM `beer-sample` WHERE brewery_id ="mishawaka_brewing";```
+       cbq> SELECT name FROM `beer-sample` WHERE brewery_id ="mishawaka_brewing";
 
 For more query samples, refer to the [Running your first N1QL query](http://developer.couchbase.com/documentation/server/4.5/getting-started/first-n1ql-query.html) guide.
 
```

**Comment by ceejatec** [comment]
Thanks! I've pushed an update.

Is there a canonical list of the Markdown supported by Docker Hub? It seems to be a restricted and slightly baroque dialect...

**Comment by ceejatec** [comment]
Hum. The Travis report says that a README file was changed, but neither of my commits touches the README.

**Comment by ceejatec** [comment]
Quick *ping* on this - can someone tell me if there's anything I can do to re-kick Travis, or...?

**Comment by yosifkit** [comment]
Thanks for the poke.  The Travis test sometimes gets grumpy when master has README changes.  Since that is the only Travis error and the PR doesn't actually have readme changes, LGTM.

**Comment by ceejatec** [comment]
Thanks!

**Pull request merged**
