### PR TITLE
update: registry docs

### PR DESCRIPTION
**Pull request by milosgajdos**
* updated links to official documentation
* updated symlink to community maintainers template

### CODE REVIEW

**Comment by thaJeztah** [comment]
Can you also update the 

- update the "maintained by Docker, Inc."; https://github.com/docker-library/docs/blob/32402675b9a03cb2e22875cc459c661faf69afd3/registry/README.md?plain=1#L19-L20
- probably remove the "need a hosted registry?" bullet (LOL, people will hate me for mentioning that, but I don't think it makes sense for the CNCF distribution project to make that recommendation); https://github.com/docker-library/docs/blob/32402675b9a03cb2e22875cc459c661faf69afd3/registry/README.md?plain=1#L25

**Comment by milosgajdos** [comment]
> update the "maintained by Docker, Inc.";

This is done by changing the symlink to a community template which I did (see the bottom file in the list)

**Comment by milosgajdos** [comment]
> probably remove the "need a hosted registry?"

Fixed in https://github.com/docker-library/docs/pull/2402/commits/8ff73b55e4ee2325d547ff745e042cf80df74f26

**Comment by thaJeztah** [comment]
> This is done by changing the symlink to a community template which I did (see the bottom file in the list)

Ah! 

```
WARNING:

    DO NOT EDIT "registry/README.md"

    IT IS AUTO-GENERATED

    (from the other files in "registry/" combined with a set of templates)
```

Hmm... but what updates the actual README then? Or does that happen on merge?

**Review by thaJeztah — COMMENTED** [review]
LGTM

**Review by yosifkit — APPROVED** [review]

**Review by tianon — APPROVED** [review]

**Comment by tianon** [comment]
`README.md` will be updated by @docker-library-bot :+1: :heart:

**Comment by thaJeztah** [comment]
Ah, thanks!

And I just realized we didn't update the reference for the "docker http api" to OCI distribution spec. I'll try to open a follow up if i find the time (no promises 🥹) https://github.com/docker-library/docs/blob/8ff73b55e4ee2325d547ff745e042cf80df74f26/registry/content.md?plain=1#L5

**Comment by milosgajdos** [comment]
Opened another PR @thaJeztah https://github.com/docker-library/docs/pull/2404

**Pull request merged**
