### PR TITLE
Update the TomEE README.md File

### PR DESCRIPTION
**Pull request by gerdogdu**
Hi all
As indicate in here http://tomee.apache.org/commercial-support.html , ManageCat is another commerical support company behind the Apache TomEE project. We would also like to include ManageCat to this README file in addition to the another commercial company Tomitribe for supporting the project.

### CODE REVIEW

**Comment by gerdogdu** [comment]
Hi all
Is anybody can help on this?
Thanks 

Gurkan-

**Comment by tianon** [comment]
cc @lordofthejars 

If @lordofthejars is OK with this change, it'll need to be moved over to `content.md` -- `README.md` is generated.

**Comment by gerdogdu** [comment]
Hi @tianon 
I have also created another pull request to update content.md file. @lordofthejars  can you please help on this new pull request #728 ?
Thanks
Gurkan

**Comment by gerdogdu** [comment]
Closing this patch. Please see #728 for merging.

**Pull request closed without merging**
