### PR TITLE
Add "VSize" to "Supported tags and respective `Dockerfile` links"

### PR DESCRIPTION
**Pull request by tianon**
Opening this for discussion.  It takes quite a long time to fetch the "virtual size", since it has to walk the entire ancestry and the registry is _really_ slow at handing back the JSON objects for each layer.

Fixes https://github.com/docker-library/java/issues/15

Here's an example from `debian`:

- [`jessie` (*jessie/Dockerfile*)](https://github.com/tianon/docker-brew-debian/blob/b34a02cb006a698c1b4be59fb1d4ba8eabc502b6/jessie/Dockerfile) [VSize: 121.8 MB]
- [`oldstable` (*oldstable/Dockerfile*)](https://github.com/tianon/docker-brew-debian/blob/b34a02cb006a698c1b4be59fb1d4ba8eabc502b6/oldstable/Dockerfile) [VSize: 78.4 MB]
- [`sid` (*sid/Dockerfile*)](https://github.com/tianon/docker-brew-debian/blob/b34a02cb006a698c1b4be59fb1d4ba8eabc502b6/sid/Dockerfile) [VSize: 121.9 MB]
- [`6.0.10`, `6.0`, `6`, `squeeze` (*squeeze/Dockerfile*)](https://github.com/tianon/docker-brew-debian/blob/b34a02cb006a698c1b4be59fb1d4ba8eabc502b6/squeeze/Dockerfile) [VSize: 78.4 MB]
- [`stable` (*stable/Dockerfile*)](https://github.com/tianon/docker-brew-debian/blob/b34a02cb006a698c1b4be59fb1d4ba8eabc502b6/stable/Dockerfile) [VSize: 85.1 MB]
- [`testing` (*testing/Dockerfile*)](https://github.com/tianon/docker-brew-debian/blob/b34a02cb006a698c1b4be59fb1d4ba8eabc502b6/testing/Dockerfile) [VSize: 121.8 MB]
- [`unstable` (*unstable/Dockerfile*)](https://github.com/tianon/docker-brew-debian/blob/b34a02cb006a698c1b4be59fb1d4ba8eabc502b6/unstable/Dockerfile) [VSize: 121.9 MB]
- [`7.7`, `7`, `wheezy`, `latest` (*wheezy/Dockerfile*)](https://github.com/tianon/docker-brew-debian/blob/b34a02cb006a698c1b4be59fb1d4ba8eabc502b6/wheezy/Dockerfile) [VSize: 85.1 MB]
- [`rc-buggy` (*debian/rc-buggy/Dockerfile*)](https://github.com/tianon/dockerfiles/blob/7ac078092e6e247b4df508c4838f314a3f749b94/debian/rc-buggy/Dockerfile) [VSize: 121.9 MB]
- [`experimental` (*debian/experimental/Dockerfile*)](https://github.com/tianon/dockerfiles/blob/7ac078092e6e247b4df508c4838f314a3f749b94/debian/experimental/Dockerfile) [VSize: 121.9 MB]

For comparison, here's `golang`:

- [`1.2.2`, `1.2` (*1.2/Dockerfile*)](https://github.com/docker-library/golang/blob/af4e450a47a99f9a4f56225cdf598f552907d946/1.2/Dockerfile) [VSize: 451.6 MB]
- [`1.2.2-onbuild`, `1.2-onbuild` (*1.2/onbuild/Dockerfile*)](https://github.com/docker-library/golang/blob/4d4b14164e50c089a09b9364697749dc7f764824/1.2/onbuild/Dockerfile) [VSize: 451.6 MB]
- [`1.2.2-cross`, `1.2-cross` (*1.2/cross/Dockerfile*)](https://github.com/docker-library/golang/blob/4d4b14164e50c089a09b9364697749dc7f764824/1.2/cross/Dockerfile) [VSize: 1.8 GB]
- [`1.3.3`, `1.3`, `1`, `latest` (*1.3/Dockerfile*)](https://github.com/docker-library/golang/blob/af4e450a47a99f9a4f56225cdf598f552907d946/1.3/Dockerfile) [VSize: 449.7 MB]
- [`1.3.3-onbuild`, `1.3-onbuild`, `1-onbuild`, `onbuild` (*1.3/onbuild/Dockerfile*)](https://github.com/docker-library/golang/blob/4d4b14164e50c089a09b9364697749dc7f764824/1.3/onbuild/Dockerfile) [VSize: 449.7 MB]
- [`1.3.3-cross`, `1.3-cross`, `1-cross`, `cross` (*1.3/cross/Dockerfile*)](https://github.com/docker-library/golang/blob/4d4b14164e50c089a09b9364697749dc7f764824/1.3/cross/Dockerfile) [VSize: 1.8 GB]
- [`1.3.3-wheezy`, `1.3-wheezy`, `1-wheezy`, `wheezy` (*1.3/wheezy/Dockerfile*)](https://github.com/docker-library/golang/blob/af4e450a47a99f9a4f56225cdf598f552907d946/1.3/wheezy/Dockerfile) [VSize: 374.4 MB]

And `java`:

- [`openjdk-6b32-jdk`, `openjdk-6b32`, `openjdk-6-jdk`, `openjdk-6`, `6b32-jdk`, `6b32`, `6-jdk`, `6` (*openjdk-6-jdk/Dockerfile*)](https://github.com/docker-library/java/blob/9b3b7ed1bdd754fa61b5dd86c0bcd3e3400c6a33/openjdk-6-jdk/Dockerfile) [VSize: 352.9 MB]
- [`openjdk-6b32-jre`, `openjdk-6-jre`, `6b32-jre`, `6-jre` (*openjdk-6-jre/Dockerfile*)](https://github.com/docker-library/java/blob/d2acc0356b5a68a4d168462a3f5f0e29444982b9/openjdk-6-jre/Dockerfile) [VSize: 203.0 MB]
- [`openjdk-7u65-jdk`, `openjdk-7u65`, `openjdk-7-jdk`, `openjdk-7`, `7u65-jdk`, `7u65`, `7-jdk`, `7`, `jdk`, `latest` (*openjdk-7-jdk/Dockerfile*)](https://github.com/docker-library/java/blob/9b3b7ed1bdd754fa61b5dd86c0bcd3e3400c6a33/openjdk-7-jdk/Dockerfile) [VSize: 562.7 MB]
- [`openjdk-7u65-jre`, `openjdk-7-jre`, `7u65-jre`, `7-jre`, `jre` (*openjdk-7-jre/Dockerfile*)](https://github.com/docker-library/java/blob/d2acc0356b5a68a4d168462a3f5f0e29444982b9/openjdk-7-jre/Dockerfile) [VSize: 308.5 MB]
- [`openjdk-8u40-jdk`, `openjdk-8u40`, `openjdk-8-jdk`, `openjdk-8`, `8u40-jdk`, `8u40`, `8-jdk`, `8` (*openjdk-8-jdk/Dockerfile*)](https://github.com/docker-library/java/blob/9b3b7ed1bdd754fa61b5dd86c0bcd3e3400c6a33/openjdk-8-jdk/Dockerfile) [VSize: 634.8 MB]
- [`openjdk-8u40-jre`, `openjdk-8-jre`, `8u40-jre`, `8-jre` (*openjdk-8-jre/Dockerfile*)](https://github.com/docker-library/java/blob/bcf0fea5a62cb2a75015e2dc2ce05bbc89afcd7d/openjdk-8-jre/Dockerfile) [VSize: 284.2 MB]

### CODE REVIEW

**Comment by yosifkit** [comment]
@tianon do we want to rebase and merge this in?

**Comment by tianon** [comment]
@yosifkit I've been giving it some more though, and while I like the extra information, I think it's visually overloading an already tightly-packed section if we add it to this top header of every image, so I'm leaning more towards a "tag details" section or something like that with this kind of information in it; what do you think?

**Comment by yosifkit** [comment]
That could be nice, but how much different would that be from the top section?  How can we simplify both sections?

**Comment by tianon** [comment]
Yeah, I guess the biggest difference would be that it wouldn't need the `Dockerfile` link, and then it wouldn't need to be quite as compressed either, so we could do something more like: (but this is apt to get really, really long, especially in the case of something like `jenkins` that has about eleven trillion tags)

## Tag Details
### `8.0`, `8`, `jessie`
- Virtual Size: 121.8 MB
- Layers: 3
- `Dockerfile`: https://github.com/tianon/docker-brew-debian/blob/b34a02cb006a698c1b4be59fb1d4ba8eabc502b6/jessie/Dockerfile

### `oldstable`
Virtual Size: 78.4 MB
Layers: 3
### `sid`
...
### `6.0.10`, `6.0`, `6`, `squeeze`
...

**Comment by denibertovic** [comment]
+1 for this...it's very much needed.

**Pull request closed without merging**
