### PR TITLE
Add Azul Zulu to list of alternative JDK's

### PR DESCRIPTION
**Pull request by HanSolo**

### CODE REVIEW

**Comment by tianon** [comment]
Thank you for the contribution! :heart:

Unfortunately, our intent with this list is to highlight other images within the program which are suitable alternatives, not to maintain a comprehensive list of all possible alternatives on Docker Hub (or even "some" - we'd have to draw the line somewhere, and it'd be hard to define that line objectively otherwise). :see_no_evil:

**Comment by HanSolo** [comment]
Hmm…understand even if I think Azul Zulu is not some unknown distribution given the fact that you also mention alternatives like Corretto or SAP Machine… 🫤

**Comment by tianon** [comment]
Right, I agree!  Zulu is definitely not an _unknown_ distribution, but it is not part of the Docker Official Images program (yet? :eyes:), for which this is the documentation, where these other implementations _are_. :sweat_smile:

**Comment by HanSolo** [comment]
Ah ok…so how could it become part of it then? 😁

**Comment by tianon** [comment]
:grinning: I'd suggest starting with a read-through of https://github.com/docker-library/official-images#contributing-to-the-standard-library -- feel free to reach out if you read through that and end up with more questions. :+1:

**Comment by HanSolo** [comment]
Will do, thx 👍🏻😁

**Comment by tianon** [comment]
(Closing for now :heart:)

**Pull request closed without merging**
