### PR TITLE
Updating the TICK stack documentation

### PR DESCRIPTION
**Pull request by jsternberg**
Fixing some small inconsistencies between them so now the documentation
is more uniform and all of the commands work correctly and are formatted
the same.

### CODE REVIEW

**Comment by yosifkit** [comment]
LGTM

**Comment by jsternberg** [comment]
I updated a single line removing the reference to the Raft port that was removed in 0.12.

**Comment by yosifkit** [comment]
LGTM

**Comment by tianon** [comment]
:+1:

**Pull request merged**
