### PR TITLE
Add "--no-prompt" flag to "push.pl"

### PR DESCRIPTION
**Pull request by tianon**
This skips the "vimdiff" invocation so that we can update directly if we know what the changeset is going to be ahead of time.

### CODE REVIEW

**Comment by yosifkit** [comment]
This seems very dangerous and will wipe-all-the-things without any feedback.

**Comment by tianon** [comment]
Indeed.  The problem I'm really solving is that `vimdiff` takes way too long to come up, and then I basically have to type `]cdo:wq` or `:%diffget\n:wq` repeatedly for every single image, and my fingers are sad.

Maybe a better solution would be to instead have a way to show a simple `diff -U` output with a simple `y/n` prompt to apply the changes?

**Comment by yosifkit** [comment]
That seems better. Maybe make it 3 options so that you can jump in vimdiff in case you want part of it.

**Comment by tianon** [comment]
Closing in favor of something new I'm working on.

**Pull request closed without merging**
