### PR TITLE
Eggdrop: Add new ENV variables to docs

### PR DESCRIPTION
**Pull request by vanosg**

### CODE REVIEW

**Comment by LaurentGoderre** [comment]
@vanosg could you try squashing/rebasing the commits down to 1?

**Comment by vanosg** [comment]
I don't know that I can once I've pushed it to my remote (without re-writing history). Do you have the option for 'Squash and Merge' under the drop down arrow on the merge button for this PR? Happy to try other options if you have suggestions, but I'd rather not re-write history if possible. Thanks!

**Comment by tianon** [comment]
For the next PR, I'd suggest cloning https://github.com/docker-library/docs.git (instead of your fork), making your changes on that, then pushing them to your fork (either by adding a remote or something like `git push git@github.com:eggheads/docs.git HEAD:some-branch-name`) which will then print out a URL for opening a PR too.

**Comment by winnieconnors** [comment]
Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Pull request closed without merging**
