### PR TITLE
typo

### PR DESCRIPTION
**Pull request by SydOps**

### CODE REVIEW

**Comment by yosifkit** [comment]
Thanks! Can you put this in `content.md` :pray: (`README.md` gets generated).

**Comment by yosifkit** [comment]
LGTM

**Comment by SydOps** [comment]
why there is cross (x) next to the latest commit?

**Comment by yosifkit** [comment]
We added a travis check to look for README.md changes and count those as errors, but since your PR had identical chanages in the content.md, it was fine.

**Pull request merged**
