### PR TITLE
Remove erroneous backslash on jetty http/2 instructions

### PR DESCRIPTION
**Pull request by devth**

### CODE REVIEW

**Comment by tianon** [comment]
Nice, LGTM

cc @md5

**Comment by md5** [comment]
Nice catch @devth!

LGTM :+1:

**Comment by yosifkit** [comment]
Aww... the change needs to be in `content.md` or the bot will just regenerate `README.md`

**Comment by devth** [comment]
Ok, I wasn't sure which one was generated. I'll fix.

**Comment by devth** [comment]
Fixed :zap:

**Comment by yosifkit** [comment]
Thanks!

**Pull request merged**
