### PR TITLE
sentry: update README to point to new repo

### PR DESCRIPTION
**Pull request by mattrobenolt**
Hi.

### CODE REVIEW

**Comment by tianon** [comment]
`README.md` is auto-generated based on the contents of the `library/sentry` file (and the list of `otherRepos` inside `update.sh`: https://github.com/docker-library/docs/blob/00b2a3f04f7cbd560041f1fcdfc9e53c45aa1060/update.sh#L23-L71) -- mind swapping this to add the new Sentry repo location there, and then update https://github.com/docker-library/official-images/blob/master/library/sentry to get the other change propagated?

**Comment by mattrobenolt** [comment]
Ah. Fancy.

**Comment by mattrobenolt** [comment]
@tianon Not entirely sure how this works, but I updated `update.sh` now, and when running, it doesn't change the content of `sentry/README.md`. :confused:

**Comment by tianon** [comment]
That should be enough :+1:

I'll follow up with the automated bot we've got on the repo to make sure it switches properly post-merge, too.

LGTM

**Comment by mattrobenolt** [comment]
Actually, don't merge yet, haha

**Comment by mattrobenolt** [comment]
Now it should be good. :+1:

**Comment by tianon** [comment]
:+1: LGTM

**Comment by tianon** [comment]
https://github.com/docker-library/docs/commit/c36faf05002c2b8339fffb6bbe5a52cf6171e8fa :+1:

**Pull request merged**
