### PR TITLE
Add documentation for new postgres initdb logic

### PR DESCRIPTION
**Pull request by tianon**
Documentation change for https://github.com/docker-library/postgres/pull/75.

### CODE REVIEW

**Comment by yosifkit** [comment]
LGTM

**Comment by md5** [comment]
It might be good to point out that `psql` commands should generally be run as user `postgres` and that no password is necessary owing to the use of `trust` authentication for a local Unix socket connection.

**Comment by tianon** [comment]
@md5 agreed; want to open an issue or PR? :innocent:

**Comment by md5** [comment]
I could probably do that. However, I think that the issue of whether `*.sql` files should be run as `postgres` or `$POSTGRES_USER` should probably be resolved first, since both of those could probably be documented at the same time.

**Comment by md5** [comment]
cf. https://github.com/docker-library/postgres/issues/81

**Comment by tianon** [comment]
:+1:

**Comment by md5** [comment]
See docker-library/postgres#82 for the entrypoint update and https://github.com/docker-library/docs/pull/319 for the docs update.

**Pull request merged**
