### PR TITLE
Remove large Vault logo from readme

### PR DESCRIPTION
**Pull request by mochanghc**
Removed a full width Vault logo that was making the page difficult to read

### CODE REVIEW

**Comment by mochanghc** [comment]
Hi I like the idea of adding the width and height. What would be the best
way to do that?

**Comment by tianon** [comment]
I think the easiest way would be updating `logo.svg` to change:

```svg
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 250 250">
```

To something like:

```svg
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 250 250" width="250" height="250">
```

... but I'd like to hear from the `vault` image maintainers for their preferences first. :sweat_smile:

re-cc @chrishoffman @jefferai @meirish :pray:

**Comment by jefferai** [comment]
@tianon None of the @'d people are maintainers on this any longer -- @kalafut @mladlow @briankassouf

**Comment by tianon** [comment]
> @tianon None of the @'d people are maintainers on this any longer -- @kalafut @mladlow @briankassouf

Doh, thanks @jefferai :facepalm:

For @kalafut @mladlow @briankassouf: it'd be great to update https://github.com/docker-library/official-images/blob/2d3e617baa553d021932a122762af7731e836d99/library/vault#L1-L3 when you get a chance :sweat_smile: :grimacing: :heart:

**Comment by kalafut** [comment]
Thanks for flagging this. We'll take a look.

**Pull request closed without merging**
