### PR TITLE
Add mention of password in the run command for Neo4j Image

### PR DESCRIPTION
**Pull request by callicles**
The neo4j image is able to change the password of the neo4j user on start up. The syntax is not very clear from the documentation.

### CODE REVIEW

**Comment by yosifkit** [comment]
cc @benbc, @spacecowboy, and @srbaker, maintainers of the neo4j image.

**Comment by spacecowboy** [comment]
@callicles please raise this issue on https://github.com/neo4j/docker-neo4j

**Comment by callicles** [comment]
@spacecowboy Should I make a pull request there ?

**Comment by spacecowboy** [comment]
@callicles I think we would prefer it if you outlined your suggested fix in an issue [here](https://github.com/neo4j/docker-neo4j) (the docker docs being here makes it kind of special).

But I can mention that we intentionally do not mention a lot of detail and instead link to our documentation: http://neo4j.com/docs/operations-manual/current/deployment/single-instance/docker/

There are several other capabilities in the container which are not mentioned in the readme for the same reason.

**Comment by benbc** [comment]
@yosifkit It seems that the problem is really that the Docker store page for Neo4j has an out-of-date version of the README: https://store.docker.com/images/5f0be9a7-f5d7-4974-9c0e-78c33484e79c. That has been updated on the Hub page (https://hub.docker.com/_/neo4j/).

**Comment by yosifkit** [comment]
As for the Docker Store page content, we are not directly involved: https://github.com/docker-library/official-images/pull/2232#issuecomment-252764305.

**Comment by spacecowboy** [comment]
The docker store page has now been updated so I think this can be closed @yosifkit

**Pull request closed without merging**
