### PR TITLE
Improve Hashicorp Vault docker run example for server mode

### PR DESCRIPTION
**Pull request by theodiefenthal**
… to actually be directly usable and fix backend to current wording of storage.

Current version leaves new user of HashiCorp image questioning on how to progress. Vault starts without any listener, doesn't open any port and is hence not usable for any quickstart or test. With this change, a user can directly call localhost:8200 in his browser and initialize and navigate in Vault UI. 

Further, its important to change wording from `backend` to `storage` as there aren't many examples of Vault JSON config out there and with the example naming the storage  `backend` it might be misleading for new users that HCL configs can't be translated easily to JSON configs.

### CODE REVIEW

**Comment by tianon** [comment]
cc `vault` image maintainers: @mladlow @calvn @ncabatoff

**Review by mladlow — COMMENTED** [review]
Thanks @theodiefenthal! I think this will make this readme easier to use.

We wanted to clarify that we wouldn't recommend this configuration in production though - would you mind making the suggested changes?

I couldn't make this a suggested change, and if you prefer I can do this myself in a follow-up PR, but we would also like to add between lines 58 & 60:

We suggest volume mounting a directory into the Docker image in order to give both the configuration and TLS certificates to Vault. You can accomplish this with:

`$ docker run --volume config/:/vault/config.d ...`

For more scalability and reliability, we suggest running containerized Vault in an orchestration environment like k8s or OpenShift.

**Comment by theodiefenthal** [comment]
Thanks for the further suggestions @mladlow , I agree that its much better to give an explicit note that the second option is also not meant for production. I hope I made all changes at your like.

**Comment by mladlow** [comment]
@theodiefenthal yes, looks good. Thank you for the improvements! @tianon I cannot approve but if you could merge this we'd appreciate it.

**Pull request merged**
