### PR TITLE
Add nuxeo image documentation

### PR DESCRIPTION
**Pull request by dmetzler**
Hello,

We would like to provide an official Nuxeo Docker image.

Thx for reviewing.

### CODE REVIEW

**Comment by Moghedrin** [comment]
LGTM, pending [#1223](https://github.com/docker-library/official-images/pull/1223).

**Comment by tianon** [comment]
Do you think it's worth noting that the default uname/pword is `Administrator`/`Administrator` here so folks trying it out don't have to search for it buried in the main Nuxeo docs?

**Comment by tianon** [comment]
LGTM :+1:

**Comment by dmetzler** [comment]
Description seems to be empty in official image, is this normal ?

**Comment by tianon** [comment]
Doh, looks like the machine doing that died; I've kicked off a temporary fix and so the description should be live within the next 30 minutes or so (possibly less).

**Pull request merged**
