### PR TITLE
Odoo: clarification of upgrading process

### PR DESCRIPTION
**Pull request by aab-odoo**
Hello,

This PR is related to #430

Regards

### CODE REVIEW

**Comment by tianon** [comment]
This is a great addition, but I think it also needs to reference both https://upgrade.odoo.com and https://github.com/OCA/OpenUpgrade in some way that makes it more clear that major version upgrades are non-trivial and that open-source/free upgrades may not necessarily even be possible unless/until implemented in the "Open Source Upgrade" repository.

**Comment by tianon** [comment]
Actually, https://doc.therp.nl/openupgrade/ is probably better to link to since it actually talks about the important stuff (unlike that Git repo's README :smile:).

**Comment by tianon** [comment]
ping @aab-odoo; have you had a chance to look at this again?

**Comment by aab-odoo** [comment]
@tianon Sorry i've been quite busy lately. I just updated the PR.

**Comment by yosifkit** [comment]
LGTM

**Comment by tianon** [comment]
Awesome, thanks! :+1:

LGTM

**Pull request merged**
