### PR TITLE
Add README config changes to enable SSL

### PR DESCRIPTION
**Pull request by stav09**
README.md missing additional httpd.conf changes to enable modules required to support SSL

### CODE REVIEW

**Comment by stav09** [comment]
I'm not sure how a valid README file update has broken the CI build...?

**Comment by yosifkit** [comment]
The CI failing is because it is complaining that you changed `readme.md` because that file is generated.  Could you put the change into `content.md` instead?

Also, all the markdown is run through tianon's fork of `markdownfmt`,  so you'll need a newline after the paragraph and before the list.  Just run `./markdownfmt.sh -d httpd/content.md` and it will give a diff if there are changes needed.

Thanks for the contribution!

**Comment by stav09** [comment]
Ah! No problems, will make the change. Thanks

**Comment by tianon** [comment]
Doing an "old/stale/stalled PRs" pass and this one's in the list, sorry!  I'm going to close, since this looks like it was forgotten. :heart: :heart:

**Pull request closed without merging**
