### PR TITLE
Update Rust examples version to 1.23.0 and fix a typo

### PR DESCRIPTION
**Pull request by shaneutt**
This is a small tweak to update the example version of Rust used in the docs (which is getting quite old) and fix a small typo.

### CODE REVIEW

**Comment by tianon** [comment]
:wink:

```markdown
 <!--
 
 ********************************************************************************
 
 WARNING:
 
     DO NOT EDIT "rust/README.md"
 
     IT IS AUTO-GENERATED
 
     (from the other files in "rust/" combined with a set of templates)
 
 ********************************************************************************
 
 -->
```

**Comment by tianon** [comment]
Also, cc @sfackler.

**Comment by sfackler** [comment]
Looks good to me, modulo the big warning :)

**Comment by shaneutt** [comment]
Should be all set now, thank you @tianon & @sfackler.

**Comment by tianon** [comment]
Thanks!

**Pull request merged**
