### PR TITLE
Add "Recommended Runtime Settings" to Docker description

### PR DESCRIPTION
**Pull request by tianon**
This is intended as an alternative approach to https://github.com/docker-library/docker/pull/258.

cc @thaJeztah @cpuguy83 @AkihiroSuda

### CODE REVIEW

**Review by cpuguy83 — COMMENTED** [review]
I would maybe preface the recommendation with some caveats:

1. By default, it will indeed inherit these values from the daemon
2. ... except in the case of ulimits *if* there are default values set on the daemon config (`--default-ulimit nofile:999999`)
3. The recommendations are how we recommend to run docker in production, and may not be needed for short-lived or non-critical instances.

**Comment by thaJeztah** [comment]
Thanks Tianon! I Forgot about opening a follow up PR 😓

Also a bit on the fence on calling it "recommended", as it really would depend on the use case 🤔

Setting OOM adjust to the same value as the daemon itself would likely not be great as it would then increase the chance that dockerd is killed before the dind container is killed.

I guess some more context to allow the user to make the right decision for their use would be good, but I know there's limited space for documentation on Hub 😔

**Comment by tianon** [comment]
Fair, thanks for the suggestions!  I did a little wordsmithing in https://github.com/docker-library/docs/compare/5dcd7c1aba4e1a5c0e5a05509bcf18a77ee58fe9..1aa9c4e79a6370d84ea88241f8b775c01a626b02 -- is this any better?

**Review by cpuguy83 — APPROVED** [review]
LGTM!

**Review by thaJeztah — APPROVED** [review]
LGTM, thanks!!

**Pull request merged**
