### PR TITLE
Handle the fallout of flattened strings from Docker 1.10+ (as best we can currently)

### PR DESCRIPTION
**Pull request by tianon**
See https://github.com/docker/docker/issues/22436 for more details.

I did my testing with `tianon/build-args:1.10.3`:

## `tianon/build-args:1.10.3`

```console
$ docker pull tianon/build-args@sha256:71cbced1991f9cde80dd208420cd74edab57044ad4f3f6a71f75742b9141815d
```

-	Total Virtual Size: 0.0 B
-	Total v2 Content-Length: 2.3 MB (2320908 bytes)

#### `2a39cddede3d258ea8cb7becb4fcd8dffe00a7d5a5340dcc9fff695ab0432882`

```dockerfile
ADD file:614a9122187935fccfa72039b9efa3ddbf371f6b029bb01e2073325f00c80b9f in /
```

-	Created: Fri, 06 May 2016 14:56:49 GMT
-	Virtual Size: 0.0 B
-	v2 Blob: `sha256:d0ca440e86378344053c79282fe959c9f288ef2ab031411295d87ef1250cfec3`
-	v2 Content-Length: 2.3 MB (2320212 bytes)
-	v2 Last-Modified: Fri, 06 May 2016 14:57:17 GMT

#### `c9e5d549ca9c919fd5b55d0cbf73cbf91a9b3bec1a2fa5014e55189504c94837`

```dockerfile
ARG test=test
```

-	Created: Wed, 18 May 2016 22:31:35 GMT
-	Parent Layer: `2a39cddede3d258ea8cb7becb4fcd8dffe00a7d5a5340dcc9fff695ab0432882`
-	Virtual Size: 0.0 B
-	v2 Blob: `sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4`
-	v2 Content-Length: 32.0 B
-	v2 Last-Modified: Sat, 14 Nov 2015 09:09:44 GMT

#### `1b058f66d9aa7a29c88caa8bbeb77a91ab7236a9dfdde78132e6c44219cf5546`

```dockerfile
# ARGS: test=test
RUN echo $test
```

-	Created: Wed, 18 May 2016 22:31:36 GMT
-	Parent Layer: `c9e5d549ca9c919fd5b55d0cbf73cbf91a9b3bec1a2fa5014e55189504c94837`
-	Virtual Size: 0.0 B
-	v2 Blob: `sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4`
-	v2 Content-Length: 32.0 B
-	v2 Last-Modified: Sat, 14 Nov 2015 09:09:44 GMT

#### `4128a7a89f4443460dfcb55c4790b7bb287d689a4a7950f035d4a45ff8979384`

```dockerfile
ENV test=test
```

-	Created: Wed, 18 May 2016 22:31:36 GMT
-	Parent Layer: `1b058f66d9aa7a29c88caa8bbeb77a91ab7236a9dfdde78132e6c44219cf5546`
-	Virtual Size: 0.0 B
-	v2 Blob: `sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4`
-	v2 Content-Length: 32.0 B
-	v2 Last-Modified: Sat, 14 Nov 2015 09:09:44 GMT

#### `c2f1e3c25f1ee841f6d4a8768c1afc570cde1ba54bbe10aae9a09c5326d3edf1`

```dockerfile
CMD ["sh" "-c" "echo $test"]
```

-	Created: Wed, 18 May 2016 22:31:36 GMT
-	Parent Layer: `4128a7a89f4443460dfcb55c4790b7bb287d689a4a7950f035d4a45ff8979384`
-	Virtual Size: 0.0 B
-	v2 Blob: `sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4`
-	v2 Content-Length: 32.0 B
-	v2 Last-Modified: Sat, 14 Nov 2015 09:09:44 GMT

#### `9d5c4fb82a5b21bf3d9d87f1f5bcfcf8484f35f3d7fb7cc54c35ab799d7bcb61`

```dockerfile
ARG a=1
```

-	Created: Wed, 18 May 2016 22:31:36 GMT
-	Parent Layer: `c2f1e3c25f1ee841f6d4a8768c1afc570cde1ba54bbe10aae9a09c5326d3edf1`
-	Virtual Size: 0.0 B
-	v2 Blob: `sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4`
-	v2 Content-Length: 32.0 B
-	v2 Last-Modified: Sat, 14 Nov 2015 09:09:44 GMT

#### `4bf5484c13caef89aba55f7ff7eec69d53985f7b5f8f8476526820f6704d70e1`

```dockerfile
ARG b=2
```

-	Created: Wed, 18 May 2016 22:31:36 GMT
-	Parent Layer: `9d5c4fb82a5b21bf3d9d87f1f5bcfcf8484f35f3d7fb7cc54c35ab799d7bcb61`
-	Virtual Size: 0.0 B
-	v2 Blob: `sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4`
-	v2 Content-Length: 32.0 B
-	v2 Last-Modified: Sat, 14 Nov 2015 09:09:44 GMT

#### `9a1ada7590f4d0afaed73c08395580f98db6328a689c0d036f007f7ea5de1420`

```dockerfile
ARG c=3
```

-	Created: Wed, 18 May 2016 22:31:36 GMT
-	Parent Layer: `4bf5484c13caef89aba55f7ff7eec69d53985f7b5f8f8476526820f6704d70e1`
-	Virtual Size: 0.0 B
-	v2 Blob: `sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4`
-	v2 Content-Length: 32.0 B
-	v2 Last-Modified: Sat, 14 Nov 2015 09:09:44 GMT

#### `f830d6cdf9896851e8d80c7a573ca4eb17f481a343e4abe71125eb28f7704764`

```dockerfile
ARG d=4
```

-	Created: Wed, 18 May 2016 22:31:37 GMT
-	Parent Layer: `9a1ada7590f4d0afaed73c08395580f98db6328a689c0d036f007f7ea5de1420`
-	Virtual Size: 0.0 B
-	v2 Blob: `sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4`
-	v2 Content-Length: 32.0 B
-	v2 Last-Modified: Sat, 14 Nov 2015 09:09:44 GMT

#### `eed2e356437347e759e77ddde4aca020daab26fa083d4131dded339d889acbd5`

```dockerfile
# ARGS: a=1 b=2 c=3 d=4
RUN echo hi
```

-	Created: Wed, 18 May 2016 22:31:37 GMT
-	Parent Layer: `f830d6cdf9896851e8d80c7a573ca4eb17f481a343e4abe71125eb28f7704764`
-	Virtual Size: 0.0 B
-	v2 Blob: `sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4`
-	v2 Content-Length: 32.0 B
-	v2 Last-Modified: Sat, 14 Nov 2015 09:09:44 GMT

#### `f465bab3cfb4e6454ee6a235c800fd0e53abcd1aa14c88aec8e31d8888a3aba5`

```dockerfile
# ARGS: a=1 b=2 c=3 d=4
RUN echo  $a $b $c $d
```

-	Created: Wed, 18 May 2016 22:31:38 GMT
-	Parent Layer: `eed2e356437347e759e77ddde4aca020daab26fa083d4131dded339d889acbd5`
-	Virtual Size: 0.0 B
-	v2 Blob: `sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4`
-	v2 Content-Length: 32.0 B
-	v2 Last-Modified: Sat, 14 Nov 2015 09:09:44 GMT

#### `ba4ab9d63137650cd6f1d108484552e9de568afba91ce005cf827a203823646d`

```dockerfile
ARG e=a b c
```

-	Created: Wed, 18 May 2016 22:31:38 GMT
-	Parent Layer: `f465bab3cfb4e6454ee6a235c800fd0e53abcd1aa14c88aec8e31d8888a3aba5`
-	Virtual Size: 0.0 B
-	v2 Blob: `sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4`
-	v2 Content-Length: 32.0 B
-	v2 Last-Modified: Sat, 14 Nov 2015 09:09:44 GMT

#### `2503ea2a8a9c6746b489e8e9ce32933215f1fcdf4dfe3e71c8415bb2969e1cdd`

```dockerfile
ARG f=a b " c
```

-	Created: Wed, 18 May 2016 22:31:38 GMT
-	Parent Layer: `ba4ab9d63137650cd6f1d108484552e9de568afba91ce005cf827a203823646d`
-	Virtual Size: 0.0 B
-	v2 Blob: `sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4`
-	v2 Content-Length: 32.0 B
-	v2 Last-Modified: Sat, 14 Nov 2015 09:09:44 GMT

#### `f9cb1933a700367692c65c698e0f1f991fb0b721d8f83eb69ec7d5dcb1a3e473`

```dockerfile
# unable to parse image command string further:
|6 a=1 b=2 c=3 d=4 e=a b c f=a b " c echo $a
```

-	Created: Wed, 18 May 2016 22:31:39 GMT
-	Parent Layer: `2503ea2a8a9c6746b489e8e9ce32933215f1fcdf4dfe3e71c8415bb2969e1cdd`
-	Virtual Size: 0.0 B
-	v2 Blob: `sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4`
-	v2 Content-Length: 32.0 B
-	v2 Last-Modified: Sat, 14 Nov 2015 09:09:44 GMT

#### `296cc5c307bf41d9ec5e66bc8ce7ddb900af204ee87c70fc1eb55ddc58478a3d`

```dockerfile
# ARGS: a=1 b=2 c=3 d=4 e=a b c f=a b " c
RUN echo "$f"
```

-	Created: Wed, 18 May 2016 22:31:40 GMT
-	Parent Layer: `f9cb1933a700367692c65c698e0f1f991fb0b721d8f83eb69ec7d5dcb1a3e473`
-	Virtual Size: 0.0 B
-	v2 Blob: `sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4`
-	v2 Content-Length: 32.0 B
-	v2 Last-Modified: Sat, 14 Nov 2015 09:09:44 GMT

#### `b1ff78317017cdfbb3a6a01a55b5c1673ca5b83c313defd8ec4053b92ffc42a6`

```dockerfile
# ARGS: a=1 b=2 c=3 d=4 e=a b c f=a b " c
RUN env > args-env
```

-	Created: Wed, 18 May 2016 22:31:40 GMT
-	Parent Layer: `296cc5c307bf41d9ec5e66bc8ce7ddb900af204ee87c70fc1eb55ddc58478a3d`
-	Virtual Size: 0.0 B
-	v2 Blob: `sha256:3f51aa2c699484092184718256f216a3b92674a29c3b1d624eb193cc9b8f708b`
-	v2 Content-Length: 216.0 B
-	v2 Last-Modified: Wed, 18 May 2016 22:31:46 GMT

#### `8419960db03531bfcf2a581a781aac3b6f8f5290c6fb8a61172403faceac06ef`

```dockerfile
# ARG: "a" => "1"
# ARG: "b" => "2"
# ARG: "c" => "3"
# ARG: "d" => "4"
# ARG: "e" => "a b c"
# ARG: "f" => "a b \" c"
RUN echo hi "$a"
```

-	Created: Wed, 18 May 2016 22:31:41 GMT
-	Parent Layer: `b1ff78317017cdfbb3a6a01a55b5c1673ca5b83c313defd8ec4053b92ffc42a6`
-	Docker Version: 1.10.3
-	Virtual Size: 0.0 B
-	v2 Blob: `sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4`
-	v2 Content-Length: 32.0 B
-	v2 Last-Modified: Sat, 14 Nov 2015 09:09:44 GMT

### CODE REVIEW

**Comment by tianon** [comment]
Ah, if the total "virtual size" of an image is zero bytes, we should probably hide that field in all layers' details. :disappointed: (given that the size information of each layer is no longer part of the manifest itself)

**Comment by tianon** [comment]
Updated output:


## `tianon/build-args:1.10.3`

```console
$ docker pull tianon/build-args@sha256:71cbced1991f9cde80dd208420cd74edab57044ad4f3f6a71f75742b9141815d
```

-	Total v2 Content-Length: 2.3 MB (2320908 bytes)

### Layers (17)

#### `2a39cddede3d258ea8cb7becb4fcd8dffe00a7d5a5340dcc9fff695ab0432882`

```dockerfile
ADD file:614a9122187935fccfa72039b9efa3ddbf371f6b029bb01e2073325f00c80b9f in /
```

-	Created: Fri, 06 May 2016 14:56:49 GMT
-	v2 Blob: `sha256:d0ca440e86378344053c79282fe959c9f288ef2ab031411295d87ef1250cfec3`
-	v2 Content-Length: 2.3 MB (2320212 bytes)
-	v2 Last-Modified: Fri, 06 May 2016 14:57:17 GMT

#### `c9e5d549ca9c919fd5b55d0cbf73cbf91a9b3bec1a2fa5014e55189504c94837`

```dockerfile
ARG test=test
```

-	Created: Wed, 18 May 2016 22:31:35 GMT
-	Parent Layer: `2a39cddede3d258ea8cb7becb4fcd8dffe00a7d5a5340dcc9fff695ab0432882`
-	v2 Blob: `sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4`
-	v2 Content-Length: 32.0 B
-	v2 Last-Modified: Sat, 14 Nov 2015 09:09:44 GMT

#### `1b058f66d9aa7a29c88caa8bbeb77a91ab7236a9dfdde78132e6c44219cf5546`

```dockerfile
# ARGS: test=test
RUN echo $test
```

-	Created: Wed, 18 May 2016 22:31:36 GMT
-	Parent Layer: `c9e5d549ca9c919fd5b55d0cbf73cbf91a9b3bec1a2fa5014e55189504c94837`
-	v2 Blob: `sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4`
-	v2 Content-Length: 32.0 B
-	v2 Last-Modified: Sat, 14 Nov 2015 09:09:44 GMT

#### `4128a7a89f4443460dfcb55c4790b7bb287d689a4a7950f035d4a45ff8979384`

```dockerfile
ENV test=test
```

-	Created: Wed, 18 May 2016 22:31:36 GMT
-	Parent Layer: `1b058f66d9aa7a29c88caa8bbeb77a91ab7236a9dfdde78132e6c44219cf5546`
-	v2 Blob: `sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4`
-	v2 Content-Length: 32.0 B
-	v2 Last-Modified: Sat, 14 Nov 2015 09:09:44 GMT

#### `c2f1e3c25f1ee841f6d4a8768c1afc570cde1ba54bbe10aae9a09c5326d3edf1`

```dockerfile
CMD ["sh" "-c" "echo $test"]
```

-	Created: Wed, 18 May 2016 22:31:36 GMT
-	Parent Layer: `4128a7a89f4443460dfcb55c4790b7bb287d689a4a7950f035d4a45ff8979384`
-	v2 Blob: `sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4`
-	v2 Content-Length: 32.0 B
-	v2 Last-Modified: Sat, 14 Nov 2015 09:09:44 GMT

#### `9d5c4fb82a5b21bf3d9d87f1f5bcfcf8484f35f3d7fb7cc54c35ab799d7bcb61`

```dockerfile
ARG a=1
```

-	Created: Wed, 18 May 2016 22:31:36 GMT
-	Parent Layer: `c2f1e3c25f1ee841f6d4a8768c1afc570cde1ba54bbe10aae9a09c5326d3edf1`
-	v2 Blob: `sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4`
-	v2 Content-Length: 32.0 B
-	v2 Last-Modified: Sat, 14 Nov 2015 09:09:44 GMT

#### `4bf5484c13caef89aba55f7ff7eec69d53985f7b5f8f8476526820f6704d70e1`

```dockerfile
ARG b=2
```

-	Created: Wed, 18 May 2016 22:31:36 GMT
-	Parent Layer: `9d5c4fb82a5b21bf3d9d87f1f5bcfcf8484f35f3d7fb7cc54c35ab799d7bcb61`
-	v2 Blob: `sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4`
-	v2 Content-Length: 32.0 B
-	v2 Last-Modified: Sat, 14 Nov 2015 09:09:44 GMT

#### `9a1ada7590f4d0afaed73c08395580f98db6328a689c0d036f007f7ea5de1420`

```dockerfile
ARG c=3
```

-	Created: Wed, 18 May 2016 22:31:36 GMT
-	Parent Layer: `4bf5484c13caef89aba55f7ff7eec69d53985f7b5f8f8476526820f6704d70e1`
-	v2 Blob: `sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4`
-	v2 Content-Length: 32.0 B
-	v2 Last-Modified: Sat, 14 Nov 2015 09:09:44 GMT

#### `f830d6cdf9896851e8d80c7a573ca4eb17f481a343e4abe71125eb28f7704764`

```dockerfile
ARG d=4
```

-	Created: Wed, 18 May 2016 22:31:37 GMT
-	Parent Layer: `9a1ada7590f4d0afaed73c08395580f98db6328a689c0d036f007f7ea5de1420`
-	v2 Blob: `sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4`
-	v2 Content-Length: 32.0 B
-	v2 Last-Modified: Sat, 14 Nov 2015 09:09:44 GMT

#### `eed2e356437347e759e77ddde4aca020daab26fa083d4131dded339d889acbd5`

```dockerfile
# ARGS: a=1 b=2 c=3 d=4
RUN echo hi
```

-	Created: Wed, 18 May 2016 22:31:37 GMT
-	Parent Layer: `f830d6cdf9896851e8d80c7a573ca4eb17f481a343e4abe71125eb28f7704764`
-	v2 Blob: `sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4`
-	v2 Content-Length: 32.0 B
-	v2 Last-Modified: Sat, 14 Nov 2015 09:09:44 GMT

#### `f465bab3cfb4e6454ee6a235c800fd0e53abcd1aa14c88aec8e31d8888a3aba5`

```dockerfile
# ARGS: a=1 b=2 c=3 d=4
RUN echo  $a $b $c $d
```

-	Created: Wed, 18 May 2016 22:31:38 GMT
-	Parent Layer: `eed2e356437347e759e77ddde4aca020daab26fa083d4131dded339d889acbd5`
-	v2 Blob: `sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4`
-	v2 Content-Length: 32.0 B
-	v2 Last-Modified: Sat, 14 Nov 2015 09:09:44 GMT

#### `ba4ab9d63137650cd6f1d108484552e9de568afba91ce005cf827a203823646d`

```dockerfile
ARG e=a b c
```

-	Created: Wed, 18 May 2016 22:31:38 GMT
-	Parent Layer: `f465bab3cfb4e6454ee6a235c800fd0e53abcd1aa14c88aec8e31d8888a3aba5`
-	v2 Blob: `sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4`
-	v2 Content-Length: 32.0 B
-	v2 Last-Modified: Sat, 14 Nov 2015 09:09:44 GMT

#### `2503ea2a8a9c6746b489e8e9ce32933215f1fcdf4dfe3e71c8415bb2969e1cdd`

```dockerfile
ARG f=a b " c
```

-	Created: Wed, 18 May 2016 22:31:38 GMT
-	Parent Layer: `ba4ab9d63137650cd6f1d108484552e9de568afba91ce005cf827a203823646d`
-	v2 Blob: `sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4`
-	v2 Content-Length: 32.0 B
-	v2 Last-Modified: Sat, 14 Nov 2015 09:09:44 GMT

#### `f9cb1933a700367692c65c698e0f1f991fb0b721d8f83eb69ec7d5dcb1a3e473`

```dockerfile
# unable to parse image command string further:
|6 a=1 b=2 c=3 d=4 e=a b c f=a b " c echo $a
```

-	Created: Wed, 18 May 2016 22:31:39 GMT
-	Parent Layer: `2503ea2a8a9c6746b489e8e9ce32933215f1fcdf4dfe3e71c8415bb2969e1cdd`
-	v2 Blob: `sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4`
-	v2 Content-Length: 32.0 B
-	v2 Last-Modified: Sat, 14 Nov 2015 09:09:44 GMT

#### `296cc5c307bf41d9ec5e66bc8ce7ddb900af204ee87c70fc1eb55ddc58478a3d`

```dockerfile
# ARGS: a=1 b=2 c=3 d=4 e=a b c f=a b " c
RUN echo "$f"
```

-	Created: Wed, 18 May 2016 22:31:40 GMT
-	Parent Layer: `f9cb1933a700367692c65c698e0f1f991fb0b721d8f83eb69ec7d5dcb1a3e473`
-	v2 Blob: `sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4`
-	v2 Content-Length: 32.0 B
-	v2 Last-Modified: Sat, 14 Nov 2015 09:09:44 GMT

#### `b1ff78317017cdfbb3a6a01a55b5c1673ca5b83c313defd8ec4053b92ffc42a6`

```dockerfile
# ARGS: a=1 b=2 c=3 d=4 e=a b c f=a b " c
RUN env > args-env
```

-	Created: Wed, 18 May 2016 22:31:40 GMT
-	Parent Layer: `296cc5c307bf41d9ec5e66bc8ce7ddb900af204ee87c70fc1eb55ddc58478a3d`
-	v2 Blob: `sha256:3f51aa2c699484092184718256f216a3b92674a29c3b1d624eb193cc9b8f708b`
-	v2 Content-Length: 216.0 B
-	v2 Last-Modified: Wed, 18 May 2016 22:31:46 GMT

#### `8419960db03531bfcf2a581a781aac3b6f8f5290c6fb8a61172403faceac06ef`

```dockerfile
# ARG: "a" => "1"
# ARG: "b" => "2"
# ARG: "c" => "3"
# ARG: "d" => "4"
# ARG: "e" => "a b c"
# ARG: "f" => "a b \" c"
RUN echo hi "$a"
```

-	Created: Wed, 18 May 2016 22:31:41 GMT
-	Parent Layer: `b1ff78317017cdfbb3a6a01a55b5c1673ca5b83c313defd8ec4053b92ffc42a6`
-	Docker Version: 1.10.3
-	v2 Blob: `sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4`
-	v2 Content-Length: 32.0 B
-	v2 Last-Modified: Sat, 14 Nov 2015 09:09:44 GMT

**Comment by yosifkit** [comment]
1. aw :cry: no `RUN` on the broken line
1. what if we are crazy and re-implement the `ARG` behavior and match the previous `ARG` definitions to the broken `RUN [...]`

Or, just get them to fix this in docker.

**Comment by tianon** [comment]
Yeah...  Given that we don't ever use `RUN [...]` in official images (that I recall), I wasn't too worried about that edge case (and definitely not worried about it to the level of considering re-implementing `Dockerfile` parsing).

**Comment by yosifkit** [comment]
LGTM

**Pull request merged**
