### PR TITLE
rename repository and tweaks

### PR DESCRIPTION
**Pull request by psftw**

### CODE REVIEW

**Comment by tianon** [comment]
Needs moar `markdownfmt` (see `markdownfmt.sh -d <some-file>` for an easy way to run this from the repo).

**Comment by psftw** [comment]
... and then the markdownfmt goblin spoke to the fearful villagers,

> Thou shalt have consistent tab indentation in code samples.

... the onlookers hesitantly nodded ...

*Suddenly, the beast belched fire and let out a terrifying roar!*

> Thou shalt not newline within a paragraph!

The crowd quickly dispersed in shock, leaving an elderly wizard, who slowly raised his magical staff with the engravement:

:arrow_forward: `gqap` :arrow_backward:

@tianon it has been done

**Comment by md5** [comment]
:crystal_ball: :sparkles: :boom: :tophat:

**Comment by tianon** [comment]
LGTM :heart_eyes:

**Comment by yosifkit** [comment]
LGTM

**Pull request merged**
