### PR TITLE
Document use of `setuid` module and user `jetty`

### PR DESCRIPTION
**Pull request by md5**

### CODE REVIEW

**Comment by tianon** [comment]
LGTM

**Comment by md5** [comment]
I just noticed that `JETTY_STATE` was still referring to `/usr/local/jetty`, so I've updated that.

I should probably change that explicitly to `/var/run/jetty` and make that a volume in another PR, but updating the docs to be correct is good enough for now.

**Comment by md5** [comment]
@yosifkit Could you PTAL? Looks like the updated Jetty image from docker-library/official-images#525 got pushed out yesterday, but not the updated docs.

Thanks! :bow:

**Comment by yosifkit** [comment]
LGTM

**Pull request merged**
