### PR TITLE
Add Sentry deprecation notice

### PR DESCRIPTION
**Pull request by BYK**
See docker-library/official-images#8673

### CODE REVIEW

**Comment by BYK** [comment]
Ping @tianon

**Comment by BYK** [comment]
@tianon I don't see the deprecation notice over at https://hub.docker.com/_/sentry/

Is there anything else we need to do?

**Comment by yosifkit** [comment]
It's not showing up because that is the "store" page that is masking the official-images page as mentioned in this [comment](https://github.com/getsentry/docker-sentry/issues/211#issuecomment-628285526). I'll try to hit some Docker folks to see if they can drop the store page part.

**Comment by mattrobenolt** [comment]
Hey @yosifkit I submit a support ticket a bunch of hours ago into Docker folks to see what needs to be done to get rid of this and haven't heard anything back yet. So maybe if you can nudge them, that'd be good. I obviously give consent. :)

**Comment by BYK** [comment]
@yosifkit @tianon is there any other channel that we should be contacting? It's been more than a week now without any updates and its been over 2 weeks since we submitted this pull request.

**Comment by mattrobenolt** [comment]
I guess also worth adding, the support ticket I submit did not get a response back.

**Comment by yosifkit** [comment]
I've poked some Docker folks again.

**Comment by yosifkit** [comment]
Docker Hub page is fixed now! :tada:

**Pull request merged**
