### PR TITLE
Add an official image for Traefik

### PR DESCRIPTION
**Pull request by emilevauge**
This is the docs PR to go  with docker-library/official-images#1476.

### CODE REVIEW

**Comment by emilevauge** [comment]
Anyone knows why tests fail sometimes?
```
[32;1mThe command "failed=''; for short in */README-short.txt; do chars="$(echo -n "$(cat "$short")" | wc -m)"; lines="$(cat "$short" | wc -l)"; if [ "$chars" -gt 100 -o "$lines" -gt 1 ]; then failed+=" $short"; fi done; if [ "$failed" ]; then echo >&2 "Too long (or too many lines):$failed"; exit 1; fi" exited with 0.[0m
travis_time:start:02d4323c
[0K$ if [ "$TRAVIS_PULL_REQUEST" != 'false' ]; then if [ "$(git diff --numstat "$TRAVIS_COMMIT_RANGE" -- '*/README.md')" ]; then echo >&2 'Error:'' at least one repo README.md has changed'; echo >&2 'These files are autogenerated, so it is unnecessary to modify them'; echo >&2 'Please update content.md and docker-library-bot will take care of README.md'; echo >&2 'See:'' https://github.com/docker-library/docs/#image-namereadmemd'; echo >&2; exit 1; fi fi
Error: at least one repo README.md has changed
These files are autogenerated, so it is unnecessary to modify them
Please update content.md and docker-library-bot will take care of README.md
See: https://github.com/docker-library/docs/#image-namereadmemd
```
/cc @tianon

**Comment by tianon** [comment]
LGTM (regarding the CI failure, I'm willing to bet it's just something funky with rebasing, and I'm happy to work out/fix that myself post-merge)

**Comment by emilevauge** [comment]
Changed the documentation URL to https://docs.traefik.io ;)

**Comment by tianon** [comment]
Nice, still LGTM :+1:

**Comment by yosifkit** [comment]
LGTM

**Pull request merged**
