### PR TITLE
Deprecate "crux" due to maintainer inactivity

### PR DESCRIPTION
**Pull request by tianon**
cc @prologic -- if we don't hear from you shortly, we'll be merging this :pray:

### CODE REVIEW

**Comment by prologic** [comment]
Please go ahead. I haven't found/made the time to do much with CRUX lately
and have mostly stopped using it as a base image in favour of alpine. I
*tried* to encourage others in the CRUX community to take over maintenance
but so far no luck :/ -- Anyone wishing ot use CRUX as a base image will
have to suffice with tooling I created and do it themselves :)


James Mills / prologic

E: prologic@shortcircuit.net.au
W: prologic.shortcircuit.net.au

**Comment by tianon** [comment]
@prologic thanks for confirming :heart: :heart: (and no hard feelings :+1:)

Perhaps this big notice at the top of the image description will help motivate someone to step up. :smiling_imp:

**Comment by prologic** [comment]
Let's hope so for the community's sake :) But let's face it; CRUX is a
pretty niche distro!

/cc @therealromster


James Mills / prologic

E: prologic@shortcircuit.net.au
W: prologic.shortcircuit.net.au

**Comment by therealromster** [comment]
I could take over this as I basically run a updated crux image, https://hub.docker.com/r/romster/crux-base-3.2/ I had no luck generating from prologic's Docker setup, I also failed with the /dev nodes making my own Docker file.

**Pull request merged**
