### PR TITLE
Add note about stack immediately after the example code

### PR DESCRIPTION
**Pull request by igrep**
A Haskell newbie loving Docker got confused by the error.
I think we should guide him/her to the section about the error near from the example code of stack.

(Retry of https://github.com/docker-library/docs/pull/1793)

### CODE REVIEW

**Comment by yosifkit** [comment]
The link will work fine here on GitHub, but will go nowhere on Docker Hub. Maybe add a "section below" so they know where to look when the link fails?

```diff
-See [Considerations for Stack](#considerations-for-stack) for details.
+See the [Considerations for Stack](#considerations-for-stack) section below for details.
```

**Comment by tianon** [comment]
(also cc `haskell` image maintainers @psftw @hvr)

**Comment by tianon** [comment]
friendly ping @psftw @hvr

**Comment by igrep** [comment]
ping

**Comment by psftw** [comment]
Sorry, I don't see the value of this change, so I'm against it.

**Pull request closed without merging**
