### PR TITLE
Reorganize "push.pl" to put the "vimdiff" logic in one place for cool dispatch-conf-alike behavior

### PR DESCRIPTION
**Pull request by tianon**
```console
$ ./push.sh ...
diff --git a/tmp/XfqXvwAiit.md b/wordpress/README.md
index df290e6..ad31c26 100644
--- a/tmp/XfqXvwAiit.md
+++ b/wordpress/README.md
@@ -69,7 +69,7 @@ The following Docker Hub features can help with the task of keeping your depende
 
 # Supported Docker versions
 
-This image is officially supported on Docker version 1.5.0.
+This image is officially supported on Docker version 1.6.0.
 
 Support for older versions (down to 1.0) is provided on a best-effort basis.
 

  1> yes
  2> vimdiff
  3> no

Apply changes? [1]: 
updating wordpress
```

### CODE REVIEW

**Comment by yosifkit** [comment]
I see the dropping of the unimplemented flag too :smile:.

**Comment by yosifkit** [comment]
LGTM

**Comment by yosifkit** [comment]
ping @Moghedrin

**Comment by tianon** [comment]
@yosifkit yeah, I figured we should remove it since it was never actually implemented and `*/` as a shell argument makes the shell do the hard work to accomplish the same goal :+1:

**Comment by Moghedrin** [comment]
LGTM :+1:

**Pull request merged**
