### PR TITLE
Added required files for nevergreen official docker image

### PR DESCRIPTION
**Pull request by manasik**
Files for nevergreen

### CODE REVIEW

**Comment by manasik** [comment]
It seems like build fails because it can't find README.md and content.md. However they have been checked in. Any ideas?

**Comment by md5** [comment]
@manasik It's finding the files, but `markdownfmt` is complaining that they have Markdown syntax issues. You'd have to run `markdownfmt -d` to see the diffs or `markdownfmt -w` to have it update the files.

**Comment by manasik** [comment]
@md5 thanks

**Comment by yosifkit** [comment]
Closing, since the related PR (https://github.com/docker-library/official-images/pull/524) was closed.

**Comment by ugurozgen** [comment]
we want to see who broke the pipeline and which stage is broken during development. How can i do this ?

**Pull request closed without merging**
