### PR TITLE
Update Readme for LTS description

### PR DESCRIPTION
**Pull request by warden**
[Review on Reviewable](https://reviewable.io/reviews/docker-library/docs/419)

### CODE REVIEW

**Comment by tianon** [comment]
`README.md` is generated from the contents of several files, primarily the official `library/jenkins` file and `content.md` (and we have a bot which regenerates this automatically on a regular cycle) -- is this PR still needed, or are we good to close?

**Comment by warden** [comment]
Sure, you can close it and it would be great if some of the info is included in the sources you mentioned.

**Comment by tianon** [comment]
Oh, this has slightly more content that's probably a good candidate for `content.md` (especially the clarification that this repo only contains LTS tags).  Sorry I missed that nuance before!

**Comment by yosifkit** [comment]
Closing old PR; feel free to comment if you feel this was closed in error.

**Pull request closed without merging**
