### PR TITLE
Odoo: document usage of docker-compose

### PR DESCRIPTION
**Pull request by sle-odoo**

### CODE REVIEW

**Comment by sle-odoo** [comment]
@tiangolo Hello,
Do you agree with my changes? If so i'll squash the commits and merge this to docker-docs.
Thank you in advance

**Comment by tiangolo** [comment]
Excellent @sle-odoo ! 

I haven't been able to check the issue with the newest versions of Postgres you commented in https://github.com/docker-library/docs/pull/720#issuecomment-262517704 but it's clearly the safest bet to just use `9.4` as you are doing.

Thanks for taking the time to review and update it! It looks good to me.

**Comment by tianon** [comment]
Nice, looks sane to me!

**Comment by sle-odoo** [comment]
thanks @tiangolo and @tianon

**Pull request merged**
