### PR TITLE
Should state what that image actually does before explaining what this is for.

### PR DESCRIPTION
**Pull request by ekevoo**
I am new to Docker, but not to Python.

I was reading the description and I was completely confused as to how it could help in any way to get a new project off the ground. This is probably not the best phrasing, but at least should be helpful to people with that background, looking for how Docker could be helpful.

Thanks.

### CODE REVIEW

**Comment by yosifkit** [comment]
Seems good to me, but readme.md is [generated](https://github.com/docker-library/docs#image-namereadmemd), so can you put it in content.md?

**Comment by ekevoo** [comment]
I noticed from the integration error message… But content.md seems to not have any mention of this at all. I'm confused! :(

**Comment by yosifkit** [comment]
Oh, silly me. This part is [generated](https://github.com/docker-library/docs/blob/master/.template-helpers/variant-onbuild.md) generically for all images that have an onbuild variant.  We should be able to customize it by copying that `variant-onbuild.md` into the python directory and adding in the changes.

**Comment by ekevoo** [comment]
Okay, I'll generate a new pull request some other time. Thanks for the pointers.

**Pull request closed without merging**
