### PR TITLE
sudo and git are needed to build ffmepg

### PR DESCRIPTION
**Pull request by dmetzler**
Small enhancement to documentation

### CODE REVIEW

**Comment by yosifkit** [comment]
I am always hesitant to recommend installing `sudo` in a container, esp when the process is already running as root, but it is up to you.  (My suggestion would be to just remove [`sudo` from your ffmeg repo](https://github.com/nuxeo/ffmpeg-nuxeo/blob/2aa906d33209374ff0e874e5fcbabca711a23fed/build-yasm.sh#L8) since you tell users to run the install scripts as root already.)

What do you think?

**Comment by dmetzler** [comment]
Hello, sorry for the late answer....

The fact is that our ffmpeg build is common to different distribution packaging and it makes uses of sudo.

**Comment by tianon** [comment]
Couldn't it be replaced by something like this? (to make the `sudo` usage conditional on whether or not we're already `root`/uid 0)
```bash
[ "$(id -u)" != 0 ] && sudo=sudo || sudo=
$sudo checkinstall --pkgname=yasm --pkgversion="1.2.0" --backup=no --deldoc=yes --default
```

**Comment by dmetzler** [comment]
Ok, I'm doing a PR like this on ffmpeg-nuxeo.

**Comment by dmetzler** [comment]
@yosifkit Can also be merged.

**Comment by yosifkit** [comment]
Looks like the travis test has a few nitpicks for some extra newlines.

**Comment by dmetzler** [comment]
@yosifkit  ok sorry, thought it was the docker image build that sometime randomly fails. It's ok now.

**Comment by tianon** [comment]
LGTM

**Pull request merged**
