### PR TITLE
Add redmine docs

### PR DESCRIPTION
**Pull request by yosifkit**

### CODE REVIEW

**Comment by psftw** [comment]
Looks good.  I think it is worth mentioning the admin/admin default account directly as it is buried deep in the upstream wiki page that is referenced.

**Comment by tianon** [comment]
@yosifkit want to add that note before, or after merge? :wink:

**Comment by yosifkit** [comment]
No need to hurry on merge, since the library-bot cannot currently auto-update docs.  I'll get this PR updated.

**Comment by yosifkit** [comment]
Updated.

**Comment by tianon** [comment]
LGTM :+1:

**Comment by tianon** [comment]
Currently stuck with https://github.com/docker/hub-beta-feedback/issues/238. :disappointed:

**Pull request merged**
