### PR TITLE
[nats-streaming] Release v0.3.8

### PR DESCRIPTION
**Pull request by kozlovic**
Essentially a bug fix release.
Details can be found [here](https://github.com/nats-io/nats-streaming-server/releases/tag/v0.3.8)

### CODE REVIEW

**Comment by kozlovic** [comment]
@tianon Wondering if I am doing something wrong because it is the second time in a row that the PR is merged but `Run update.sh` is not started after the PR is merged, which leaves the docker up with new tag but old doc (see reference to v0.3.6 in [here](https://hub.docker.com/_/nats-streaming/)).

**Comment by tianon** [comment]
@kozlovic arg, looks like our updater is having an issue: https://doi-janky.infosiftr.net/job/docs/job/update/

Thanks for pointing it out -- I'll go dig in and see if I can get it fixed now. :heart:

**Comment by tianon** [comment]
Looks like I got it working again.  Did some updates yesterday on the Jenkins server which caused the issue. :disappointed:

**Comment by kozlovic** [comment]
I saw it is updated, thanks!

**Pull request merged**
